pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io

// Color contract for the dedicated wallpaper instance.
// Colors are generated by the theme-system QuickshellWallpaperTheme plugin into
// ~/.config/quickshell/wallpaper/colors.json and reloaded via the
// `theme-manager` IPC target in shell.qml.
QtObject {
    id: root

    readonly property string fontFamily: "JetBrainsMono Nerd Font"

    // Material Design 3 tokens (overwritten from colors.json when available).
    property color background: "#1e1e2e"
    property color error: "#f38ba8"
    property color error_container: "#313244"
    property color inverse_on_surface: "#1e1e2e"
    property color inverse_primary: "#cba6f7"
    property color inverse_surface: "#cdd6f4"
    property color on_background: "#cdd6f4"
    property color on_error: "#11111b"
    property color on_error_container: "#cdd6f4"
    property color on_primary: "#11111b"
    property color on_primary_container: "#cdd6f4"
    property color on_primary_fixed: "#11111b"
    property color on_primary_fixed_variant: "#11111b"
    property color on_secondary: "#11111b"
    property color on_secondary_container: "#cdd6f4"
    property color on_secondary_fixed: "#11111b"
    property color on_secondary_fixed_variant: "#11111b"
    property color on_surface: "#cdd6f4"
    property color on_surface_variant: "#bac2de"
    property color on_tertiary: "#11111b"
    property color on_tertiary_container: "#cdd6f4"
    property color on_tertiary_fixed: "#11111b"
    property color on_tertiary_fixed_variant: "#11111b"
    property color outline: "#6c7086"
    property color outline_variant: "#585b70"
    property color primary: "#cba6f7"
    property color primary_container: "#313244"
    property color primary_fixed: "#cba6f7"
    property color primary_fixed_dim: "#cba6f7"
    property color scrim: "#000000"
    property color secondary: "#89b4fa"
    property color secondary_container: "#313244"
    property color secondary_fixed: "#89b4fa"
    property color secondary_fixed_dim: "#89b4fa"
    property color shadow: "#000000"
    property color source_color: "#cba6f7"
    property color surface: "#1e1e2e"
    property color surface_bright: "#45475a"
    property color surface_container: "#1e1e2e"
    property color surface_container_high: "#313244"
    property color surface_container_highest: "#45475a"
    property color surface_container_low: "#181825"
    property color surface_container_lowest: "#11111b"
    property color surface_dim: "#181825"
    property color surface_tint: "#cba6f7"
    property color surface_variant: "#313244"
    property color tertiary: "#a6e3a1"
    property color tertiary_container: "#313244"
    property color tertiary_fixed: "#a6e3a1"
    property color tertiary_fixed_dim: "#a6e3a1"

    property var themeReader: Process {
        id: reader
        command: ["bash", "-c", "cat \"$HOME/.config/quickshell/wallpaper/colors.json\" 2>/dev/null"]
        stdout: StdioCollector {
            onStreamFinished: {
                const output = this.text.trim();
                if (output === "")
                    return;
                try {
                    const newColors = JSON.parse(output);
                    for (const key in newColors) {
                        if (root.hasOwnProperty(key) && key !== "objectName") {
                            root[key] = newColors[key];
                        }
                    }
                } catch (e) {
                    console.log("Wallpaper theme JSON parse failed: " + e);
                }
            }
        }
    }

    function reloadTheme() {
        reader.running = false;
        reader.running = true;
    }

    Component.onCompleted: reloadTheme()
}
