#!/usr/bin/env -S uv run
# /// script
# requires-python = ">=3.11"
# dependencies = ["click>=8.0", "pyyaml>=6.0", "rich>=13.0"]
# ///

"""Universal Theme Manager - Matugen Only"""

import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
import click
import yaml
from rich.console import Console

console = Console()

# Paths
HOME = Path.home()
CHEZMOI_SOURCE = HOME / ".local/share/chezmoi"
CONFIG_HOME = HOME / ".config"
THEME_DATA = CHEZMOI_SOURCE / ".chezmoidata/theme.yaml"
WALLPAPER_DATA = CHEZMOI_SOURCE / ".chezmoidata/wallpaper-state.yaml"
THEMES_DIR = CHEZMOI_SOURCE / "dot_config/theme-system/themes"
WEZTERM_COLORS = CONFIG_HOME / "wezterm/colors-wezterm.lua"
WEZTERM_TRANSPARENCY = CONFIG_HOME / "wezterm/transparency-wezterm.lua"
MATUGEN_CACHE = HOME / ("Library/Caches" if sys.platform == "darwin" else ".cache") / "matugen/colors.json"
LOCK_FILE = HOME / ".cache/theme-system-running"


def load_yaml(path: Path) -> dict:
    if not path.exists():
        return {}
    with open(path) as f:
        return yaml.safe_load(f) or {}


def save_yaml(path: Path, data: dict):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, 'w') as f:
        yaml.dump(data, f, default_flow_style=False)


def generate_wezterm_colors(theme_data: dict):
    """Generate colors-wezterm.lua directly from theme data"""
    theme = theme_data.get('theme', {})
    theme_name = theme.get('name', 'mocha')
    
    console.print("[blue]🎨 Generating WezTerm colors...[/blue]")
    
    # Generate Lua file content
    if theme_name == 'dynamic':
        # Dynamic theme: Material Design 3 colors
        mat = theme.get('material', {})
        lua_content = f"""-- WezTerm Colors - Generated by theme system
-- Dynamic theme: Material Design 3 from wallpaper

local colors = {{}}

-- Basic
colors.foreground = "{mat.get('on_surface', '#cdd6f4')}"
colors.background = "{mat.get('background', '#1e1e2e')}"

-- Cursor
colors.cursor_bg = "{mat.get('primary', '#cba6f7')}"
colors.cursor_fg = "{mat.get('on_primary', '#11111b')}"
colors.cursor_border = "{mat.get('primary', '#cba6f7')}"

-- Selection
colors.selection_bg = "{mat.get('primary_container', '#45475a')}"
colors.selection_fg = "{mat.get('on_primary_container', '#cdd6f4')}"

-- ANSI colors (Material Design 3 → Terminal mapping)
colors.ansi = {{
  "{mat.get('surface', '#1e1e2e')}",              -- black
  "{mat.get('error', '#f38ba8')}",                -- red
  "{mat.get('tertiary', '#a6e3a1')}",             -- green
  "{mat.get('secondary_container', '#313244')}",  -- yellow
  "{mat.get('primary', '#cba6f7')}",              -- blue
  "{mat.get('secondary', '#89b4fa')}",            -- magenta
  "{mat.get('tertiary_container', '#313244')}",   -- cyan
  "{mat.get('on_surface', '#cdd6f4')}",           -- white
}}

colors.brights = {{
  "{mat.get('surface_variant', '#313244')}",
  "{mat.get('error', '#f38ba8')}",
  "{mat.get('tertiary', '#a6e3a1')}",
  "{mat.get('secondary_container', '#313244')}",
  "{mat.get('primary', '#cba6f7')}",
  "{mat.get('secondary', '#89b4fa')}",
  "{mat.get('tertiary_container', '#313244')}",
  "{mat.get('on_surface_variant', '#bac2de')}",
}}

return colors
"""
    else:
        # Static theme: Catppuccin with Mauve accents
        ctp = theme.get('colors', {})
        lua_content = f"""-- WezTerm Colors - Generated by theme system
-- Static theme: Catppuccin {theme_name.title()} with Mauve accents

local colors = {{}}

-- Basic
colors.foreground = "{ctp.get('text', '#cdd6f4')}"
colors.background = "{ctp.get('base', '#1e1e2e')}"

-- Cursor
colors.cursor_bg = "{ctp.get('mauve', '#cba6f7')}"
colors.cursor_fg = "{ctp.get('crust', '#11111b')}"
colors.cursor_border = "{ctp.get('mauve', '#cba6f7')}"

-- Selection
colors.selection_bg = "{ctp.get('surface2', '#585b70')}"
colors.selection_fg = "{ctp.get('text', '#cdd6f4')}"

-- Split border
colors.split = "{ctp.get('mauve', '#cba6f7')}"

-- Catppuccin ANSI colors
colors.ansi = {{
  "{ctp.get('surface1', '#45475a')}",  -- black
  "{ctp.get('red', '#f38ba8')}",       -- red
  "{ctp.get('green', '#a6e3a1')}",     -- green
  "{ctp.get('yellow', '#f9e2af')}",    -- yellow
  "{ctp.get('blue', '#89b4fa')}",      -- blue
  "{ctp.get('mauve', '#cba6f7')}",     -- magenta (Mauve!)
  "{ctp.get('teal', '#94e2d5')}",      -- cyan
  "{ctp.get('subtext1', '#bac2de')}",  -- white
}}

colors.brights = {{
  "{ctp.get('surface2', '#585b70')}",  -- bright black
  "{ctp.get('red', '#f38ba8')}",       -- bright red
  "{ctp.get('green', '#a6e3a1')}",     -- bright green
  "{ctp.get('yellow', '#f9e2af')}",    -- bright yellow
  "{ctp.get('blue', '#89b4fa')}",      -- bright blue
  "{ctp.get('mauve', '#cba6f7')}",     -- bright magenta (Mauve!)
  "{ctp.get('teal', '#94e2d5')}",      -- bright cyan
  "{ctp.get('subtext0', '#a6adc8')}",  -- bright white
}}

return colors
"""
    
    # Write the file
    WEZTERM_COLORS.parent.mkdir(parents=True, exist_ok=True)
    with open(WEZTERM_COLORS, 'w') as f:
        f.write(lua_content)
    
    console.print(f"[green]✓ Generated {WEZTERM_COLORS}[/green]")


def generate_wezterm_transparency(theme_data: dict):
    """Generate transparency-wezterm.lua from theme data"""
    theme = theme_data.get('theme', {})
    transparency = theme.get('transparency', 0)
    
    if transparency > 0:
        opacity = transparency / 100.0
        lua_content = f"""-- WezTerm Transparency - Generated by theme system
-- Transparency: {transparency}%

return {{
  enabled = true,
  opacity = {opacity},
  blur = 80,
}}
"""
    else:
        lua_content = """-- WezTerm Transparency - Generated by theme system
-- Transparency: disabled

return {
  enabled = false,
}
"""
    
    # Write the file
    WEZTERM_TRANSPARENCY.parent.mkdir(parents=True, exist_ok=True)
    with open(WEZTERM_TRANSPARENCY, 'w') as f:
        f.write(lua_content)
    
    console.print(f"[green]✓ Generated {WEZTERM_TRANSPARENCY}[/green]")


def extract_colors_matugen(wallpaper_path: Path) -> dict:
    """Extract colors using matugen only"""
    console.print("[blue]🎨 Extracting colors from wallpaper...[/blue]")
    
    try:
        result = subprocess.run(
            ['matugen', 'image', str(wallpaper_path), '-m', 'dark', '--json', 'hex'],
            check=True,
            capture_output=True,
            text=True
        )
        
        data = json.loads(result.stdout)
        
        console.print("[green]✓ Matugen: Material Design 3 palette generated[/green]")
        
        # Extract dark mode colors
        colors = data.get('colors', {}).get('dark', {})
        
        return colors
        
    except Exception as e:
        raise click.ClickException(f"Matugen failed: {e}")


@click.group()
def cli():
    """Universal Theme Manager"""
    pass


@cli.command()
@click.argument('name')
@click.option('-t', '--transparency', type=click.IntRange(0, 100), default=None)
def set(name: str, transparency: int | None):
    """Set theme: mocha, latte, frappe, macchiato, dynamic"""
    
    # Lock
    if LOCK_FILE.exists():
        raise click.ClickException("Already running")
    LOCK_FILE.parent.mkdir(parents=True, exist_ok=True)
    LOCK_FILE.touch()
    
    try:
        valid = ['mocha', 'latte', 'frappe', 'macchiato', 'dynamic']
        if name not in valid:
            raise click.ClickException(f"Invalid theme. Valid: {', '.join(valid)}")
        
        theme_data = load_yaml(THEME_DATA)
        
        # If transparency not specified, preserve current transparency
        if transparency is None:
            transparency = theme_data.get('theme', {}).get('transparency', 0)
        
        if name == 'dynamic':
            console.print("[blue]🌈 Dynamic theme...[/blue]")
            
            # Get wallpaper
            wallpaper_state = load_yaml(WALLPAPER_DATA)
            wallpaper_path = wallpaper_state.get('wallpaper', {}).get('current')
            
            if not wallpaper_path or not Path(wallpaper_path).exists():
                raise click.ClickException("No wallpaper set. Run 'wallpaper set <path>' first.")
            
            # Extract colors
            material_colors = extract_colors_matugen(Path(wallpaper_path))
            
            theme_data['theme'] = {
                'name': 'dynamic',
                'variant': 'dark',
                'transparency': transparency,
                'last_updated': datetime.now(timezone.utc).isoformat(),
                'material': material_colors,
                'source_wallpaper': str(wallpaper_path),
            }
        else:
            console.print(f"[blue]🎨 Theme: {name}[/blue]")
            
            # Load Catppuccin theme
            theme_file = THEMES_DIR / f"catppuccin-{name}.json"
            with open(theme_file) as f:
                theme_json = json.load(f)
            
            ctp = theme_json['colors']
            
            # Map to Material Design 3
            material_colors = {
                'primary': ctp['mauve'],
                'on_primary': ctp['crust'],
                'primary_container': ctp['surface0'],
                'on_primary_container': ctp['text'],
                'secondary': ctp['blue'],
                'on_secondary': ctp['crust'],
                'secondary_container': ctp['surface0'],
                'on_secondary_container': ctp['text'],
                'tertiary': ctp['green'],
                'on_tertiary': ctp['crust'],
                'tertiary_container': ctp['surface0'],
                'on_tertiary_container': ctp['text'],
                'error': ctp['red'],
                'on_error': ctp['crust'],
                'error_container': ctp['surface0'],
                'on_error_container': ctp['text'],
                'background': ctp['base'],
                'on_background': ctp['text'],
                'surface': ctp['base'],
                'on_surface': ctp['text'],
                'surface_variant': ctp['surface0'],
                'on_surface_variant': ctp['subtext1'],
                'surface_dim': ctp['mantle'],
                'surface_bright': ctp['surface1'],
                'surface_container_lowest': ctp['crust'],
                'surface_container_low': ctp['mantle'],
                'surface_container': ctp['base'],
                'surface_container_high': ctp['surface0'],
                'surface_container_highest': ctp['surface1'],
                'outline': ctp['overlay0'],
                'outline_variant': ctp['surface2'],
                'shadow': '#000000',
                'scrim': '#000000',
                'inverse_surface': ctp['text'],
                'inverse_on_surface': ctp['base'],
                'inverse_primary': ctp['mauve'],
            }
            
            theme_data['theme'] = {
                'name': name,
                'variant': theme_json.get('variant', 'dark'),
                'transparency': transparency,
                'last_updated': datetime.now(timezone.utc).isoformat(),
                'colors': ctp,
                'material': material_colors,
            }
        
        # Save state (for reproducibility)
        save_yaml(THEME_DATA, theme_data)
        console.print("[green]✓ Theme state saved[/green]")
        
        # Generate config files directly (fast & surgical)
        generate_wezterm_colors(theme_data)
        generate_wezterm_transparency(theme_data)
        
        # Wait for WezTerm to pick up changes
        import time
        time.sleep(2)
        
        console.print(f"[green]✅ Theme '{name}' applied[/green]")
        
    finally:
        LOCK_FILE.unlink(missing_ok=True)


@cli.command()
def toggle():
    """Toggle between mocha and latte"""
    theme_data = load_yaml(THEME_DATA)
    current = theme_data.get('theme', {}).get('name', 'mocha')
    transparency = theme_data.get('theme', {}).get('transparency', 0)
    
    new_theme = 'latte' if current == 'mocha' else 'mocha'
    
    ctx = click.Context(set)
    ctx.invoke(set, name=new_theme, transparency=transparency)


@cli.command()
def status():
    """Show current theme"""
    theme_data = load_yaml(THEME_DATA)
    theme = theme_data.get('theme', {})
    
    console.print(f"\n[bold]🎨 Current Theme[/bold]")
    console.print(f"  Name: {theme.get('name', 'none')}")
    console.print(f"  Variant: {theme.get('variant', 'unknown')}")
    console.print(f"  Transparency: {theme.get('transparency', 0)}%")
    console.print()


@cli.command()
@click.argument('value', type=click.IntRange(0, 100))
def transparency(value: int):
    """Change transparency without changing theme"""
    theme_data = load_yaml(THEME_DATA)
    current_theme = theme_data.get('theme', {}).get('name', 'mocha')
    
    console.print(f"[blue]🔲 Setting transparency to {value}%...[/blue]")
    
    # Re-apply current theme with new transparency
    ctx = click.Context(set)
    ctx.invoke(set, name=current_theme, transparency=value)


if __name__ == '__main__':
    cli()
