-- Opacity Manager
-- Applies opacity settings after colorscheme loads
-- Triggered by ColorScheme autocmd

local M = {}

--- Apply opacity settings based on current environment
local function apply_opacity()
  -- Load opacity data (generated by theme-manager.py)
  local ok, opacity_data = pcall(require, 'config.opacity-data')
  if not ok then
    -- Fallback to defaults
    opacity_data = { opacity = 1.0, opacity_percent = 100 }
  end
  
  if vim.g.neovide then
    -- Neovide: Direct opacity control via vim.g variables
    vim.g.neovide_opacity = opacity_data.opacity
    vim.g.neovide_normal_opacity = opacity_data.opacity
    
    -- Enable blur effects when opacity < 100%
    if opacity_data.opacity < 1.0 then
      vim.g.neovide_window_blurred = true
      vim.g.neovide_floating_blur_amount_x = 2.0
      vim.g.neovide_floating_blur_amount_y = 2.0
      vim.g.neovide_floating_shadow = true
      vim.g.neovide_floating_corner_radius = 0.3
    else
      vim.g.neovide_window_blurred = false
    end
    
    -- Cursor configuration for better visibility
    vim.g.neovide_cursor_animation_length = 0.13
    vim.g.neovide_cursor_trail_size = 0.8
    vim.g.neovide_cursor_antialiasing = true
    vim.g.neovide_cursor_animate_in_insert_mode = true
    vim.g.neovide_cursor_animate_command_line = true
    vim.g.neovide_cursor_unfocused_outline_width = 0.125
    
    -- Cursor VFX for visibility (especially with transparency)
    vim.g.neovide_cursor_vfx_mode = "railgun"
    vim.g.neovide_cursor_vfx_opacity = 200.0
    vim.g.neovide_cursor_vfx_particle_lifetime = 1.2
    vim.g.neovide_cursor_vfx_particle_density = 7.0
    
    -- Set guicursor explicitly to ensure Cursor highlight is used
    vim.opt.guicursor = 'n-v-c-sm:block-Cursor,i-ci-ve:ver25-Cursor,r-cr-o:hor20-Cursor,t:block-Cursor'
    
    -- Ensure Cursor highlight persists across colorscheme changes
    vim.defer_fn(function()
      local cursor_hl = vim.api.nvim_get_hl(0, { name = "Cursor" })
      if not cursor_hl.bg then
        -- Fallback: Try to get mauve from current colorscheme
        local catppuccin_ok, catppuccin_colors = pcall(require, "catppuccin.palettes")
        if catppuccin_ok then
          local palette = catppuccin_colors.get_palette()
          if palette and palette.mauve then
            vim.api.nvim_set_hl(0, "Cursor", { fg = palette.base, bg = palette.mauve })
          end
        end
      end
    end, 100)
  else
    -- Terminal: Manual transparency for non-Catppuccin themes
    -- (Catppuccin's transparent_background is handled in plugin config)
    local colorscheme = vim.g.colors_name or ""
    if not colorscheme:match("^catppuccin") and opacity_data.opacity < 1.0 then
      vim.api.nvim_set_hl(0, "Normal", { bg = "NONE" })
      vim.api.nvim_set_hl(0, "NormalFloat", { bg = "NONE" })
      vim.api.nvim_set_hl(0, "SignColumn", { bg = "NONE" })
    end
  end
end

--- Reload opacity (for external calls, e.g., from file watcher)
function M.reload()
  -- Unload cached opacity data
  package.loaded['config.opacity-data'] = nil
  
  -- Directly apply new opacity
  apply_opacity()
end

--- Initialize opacity manager
function M.setup()
  -- Apply opacity after every colorscheme change
  vim.api.nvim_create_autocmd('ColorScheme', {
    group = vim.api.nvim_create_augroup('OpacityManager', { clear = true }),
    callback = apply_opacity,
    desc = "Apply opacity settings after colorscheme loads"
  })
  
  -- Apply on startup
  apply_opacity()
end

return M
