"""Color conversion and manipulation utilities"""


def hex_to_argb(hex_color: str, alpha: str = "ff") -> str:
    """Convert #RRGGBB to 0xAARRGGBB format
    
    Args:
        hex_color: Hex color string (with or without #)
        alpha: Alpha channel as hex (00-FF), default FF (opaque)
        
    Returns:
        Color in 0xAARRGGBB format
        
    Examples:
        >>> hex_to_argb("#1e1e2e")
        '0xff1e1e2e'
        >>> hex_to_argb("cba6f7", "a5")
        '0xa5cba6f7'
    """
    hex_clean = hex_color.lstrip("#")
    return f"0x{alpha}{hex_clean}"


def opacity_to_alpha(opacity_percent: int, format: str = "hex") -> str | float:
    """Convert 0-100 opacity percentage to alpha value
    
    Args:
        opacity_percent: 0-100 where 0=transparent, 100=opaque
        format: Output format - 'hex' (0xNN) or 'float' (0.0-1.0)
        
    Returns:
        Alpha value in requested format
        
    Examples:
        >>> opacity_to_alpha(65, "hex")
        '0xa6'
        >>> opacity_to_alpha(65, "float")
        0.65
        >>> opacity_to_alpha(0, "hex")
        '0x00'
        >>> opacity_to_alpha(100, "float")
        1.0
    """
    if format == "hex":
        alpha_int = int(opacity_percent * 255 / 100)
        return f"0x{alpha_int:02x}"
    elif format == "float":
        return opacity_percent / 100.0
    else:
        raise ValueError(f"Invalid format: {format}. Use 'hex' or 'float'")


def hex_to_css_rgba(hex_color: str, alpha: float = 1.0) -> str:
    """Convert #RRGGBB to GTK/CSS 'rgba(r, g, b, a)' form (matugen-compatible).

    Examples:
        >>> hex_to_css_rgba("#1e1e2e", 0.3)
        'rgba(30, 30, 46, 0.3)'
    """
    h = hex_color.lstrip("#")
    r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
    a = ("%.6f" % alpha).rstrip("0").rstrip(".")
    return f"rgba({r}, {g}, {b}, {a})"


def build_css_palette(material: dict, opacity: int = 100) -> str:
    """Build the generic GTK `@define-color` palette consumed by swaync, walker
    and wlogout stylesheets.

    Compatible with ML4W's matugen `colors.css` template (every Material Design 3
    role as `@define-color <name> <hex>;`, preceded by the two fixed blur
    backgrounds), and additionally emits opacity-driven panel backgrounds derived
    from the theme's opacity setting so each panel honours the opacity slider:

        @define-color window_alpha       rgba(surface,     opacity)
        @define-color window_alpha_dim   rgba(surface_dim, opacity)

    Args:
        material: Material Design 3 color roles (hex).
        opacity: 0-100 (0=invisible, 100=solid) -> panel background alpha.
    """
    surface = material.get("surface", "#1e1e2e")
    surface_dim = material.get("surface_dim", surface)
    op = max(0, min(100, opacity)) / 100.0
    # "Soft" opacity for panels that can't be backed by a blur (walker box,
    # floating notifications, wlogout): GTK/CSS has no backdrop-filter, so
    # instead of letting them go see-through and unreadable, we keep them mostly
    # solid — 100% at full opacity, dropping by at most 20 points (to 80%) at
    # opacity 0.
    soft = 1.0 - (1.0 - op) * 0.20

    palette = dict(material)
    # matugen always emits these two; static (catppuccin) maps don't, so alias
    # them to primary so any stylesheet referencing them still resolves.
    palette.setdefault("source_color", material.get("primary", "#cba6f7"))
    palette.setdefault("surface_tint", material.get("primary", "#cba6f7"))

    lines = [
        "/*",
        "* CSS Colors",
        "* Generated by theme-system",
        "*/",
        f"@define-color blur_background {hex_to_css_rgba(surface, 0.3)};",
        f"@define-color blur_background8 {hex_to_css_rgba(surface, 0.8)};",
        f"@define-color window_alpha {hex_to_css_rgba(surface, op)};",
        f"@define-color window_alpha_dim {hex_to_css_rgba(surface_dim, op)};",
        f"@define-color window_alpha_soft {hex_to_css_rgba(surface, soft)};",
        f"@define-color window_alpha_soft_dim {hex_to_css_rgba(surface_dim, soft)};",
    ]
    lines += [f"@define-color {name} {value};" for name, value in palette.items()]
    return "\n".join(lines) + "\n"


# libadwaita named-color roles -> Material Design 3 roles.
# Ported verbatim from ML4W's matugen `gtk-colors.css` template.
_GTK_LIBADWAITA_MAP = {
    "accent_color": "primary_fixed_dim",
    "accent_fg_color": "on_primary_fixed",
    "accent_bg_color": "primary_fixed_dim",
    "window_bg_color": "surface_dim",
    "window_fg_color": "on_surface",
    "headerbar_bg_color": "surface_dim",
    "headerbar_fg_color": "on_surface",
    "popover_bg_color": "surface_dim",
    "popover_fg_color": "on_surface",
    "view_bg_color": "surface",
    "view_fg_color": "on_surface",
    "card_bg_color": "surface",
    "card_fg_color": "on_surface",
}


def build_gtk_palette(material: dict) -> str:
    """Build the libadwaita `@define-color` overrides for GTK3/GTK4.

    Ported from ML4W's matugen `gtk-colors.css` template so adopted GTK configs
    (which `@import 'colors.css'`) keep their accent/window/headerbar theming.
    """
    lines = ["/*", "* GTK Colors", "* Generated by theme-system", "*/"]
    for css_name, role in _GTK_LIBADWAITA_MAP.items():
        lines.append(f"@define-color {css_name} {material.get(role, '#cba6f7')};")
    lines += [
        "@define-color sidebar_bg_color @window_bg_color;",
        "@define-color sidebar_fg_color @window_fg_color;",
        "@define-color sidebar_border_color @window_bg_color;",
        "@define-color sidebar_backdrop_color @window_bg_color;",
    ]
    return "\n".join(lines) + "\n"


# GTK3 (Adwaita) named colors. GTK3 apps (Thunar et al.) read these @theme_*
# names, NOT libadwaita's window_bg_color/accent_color, so they are required for
# GTK3 to actually follow the palette (dark background + MD3 accents).
_GTK3_NAMED_MAP = {
    "theme_bg_color": "surface_dim",
    "theme_fg_color": "on_surface",
    "theme_base_color": "surface",
    "theme_text_color": "on_surface",
    "theme_selected_bg_color": "primary_fixed_dim",
    "theme_selected_fg_color": "on_primary_fixed",
    "theme_unfocused_bg_color": "surface_dim",
    "theme_unfocused_fg_color": "on_surface_variant",
    "theme_unfocused_base_color": "surface",
    "theme_unfocused_text_color": "on_surface_variant",
    "theme_unfocused_selected_bg_color": "primary_fixed_dim",
    "theme_unfocused_selected_fg_color": "on_primary_fixed",
    "insensitive_bg_color": "surface_container",
    "insensitive_fg_color": "outline",
    "insensitive_base_color": "surface_dim",
    "borders": "outline_variant",
    "unfocused_borders": "outline_variant",
    "warning_color": "secondary",
    "error_color": "error",
    "success_color": "tertiary",
}


def build_gtk3_palette(material: dict) -> str:
    """Build GTK3 (Adwaita) `@theme_*` `@define-color` overrides.

    Appended to the gtk-3.0 colors.css alongside the libadwaita names so GTK3
    apps (Thunar) get a dark, themed surface on top of the Adwaita(-dark) base.
    """
    lines = ["", "/* GTK3 (Adwaita) named colors — required for GTK3 apps */"]
    for css_name, role in _GTK3_NAMED_MAP.items():
        lines.append(f"@define-color {css_name} {material.get(role, '#cba6f7')};")
    return "\n".join(lines) + "\n"
