"""Atuin theme generator"""

from pathlib import Path
from .base import BaseApp
from utils import get_material_colors, get_catppuccin_colors, is_dynamic_theme


class AtuinTheme(BaseApp):
    """Atuin TUI shell history tool theme generator
    
    Generates:
    - Theme files in ~/.config/atuin/themes/ (TOML format)
    - Updates main config's [theme] name reference
    
    Atuin loads config fresh on each invocation, so changes take effect
    on next shell invocation or when running any atuin command.
    """
    
    def __init__(self, config_home: Path):
        super().__init__("Atuin", config_home)
        self.themes_dir = config_home / "atuin/themes"
        self.config_file = config_home / "atuin/config.toml"
    
    def apply_theme(self, theme_data: dict) -> None:
        """Apply theme to Atuin"""
        theme_name = self.generate_theme_file(theme_data)
        self.update_config_reference(theme_name)
        self.log_reload_instructions()
    
    def generate_theme_file(self, theme_data: dict) -> str:
        """Generate theme file in TOML format
        
        Returns:
            Theme name (filename without .toml extension)
        """
        self.log_progress("Generating Atuin theme")
        
        if is_dynamic_theme(theme_data):
            content, theme_name = self._generate_dynamic_theme(theme_data)
        else:
            content, theme_name = self._generate_static_theme(theme_data)
        
        # Write to ~/.config/atuin/themes/{theme_name}.toml
        theme_file = self.themes_dir / f"{theme_name}.toml"
        self.write_file(theme_file, content)
        
        return theme_name
    
    def update_config_reference(self, theme_name: str) -> None:
        """Update [theme] name in main config using tomlkit
        
        Args:
            theme_name: Name of theme to reference (without .toml extension)
        """
        try:
            import tomlkit
        except ImportError:
            self.log_warning("tomlkit not available, skipping config update")
            self.log_warning(f"Manually set: [theme] name = \"{theme_name}\"")
            return
        
        if not self.config_file.exists():
            self.log_warning(f"Atuin config not found: {self.config_file}")
            return
        
        # Read existing config
        with open(self.config_file, 'r') as f:
            config = tomlkit.load(f)
        
        # Update theme name (preserves comments)
        if 'theme' not in config:
            config['theme'] = {}
        
        old_name = config.get('theme', {}).get('name', 'none')
        config['theme']['name'] = theme_name
        
        # Write back
        with open(self.config_file, 'w') as f:
            tomlkit.dump(config, f)
        
        self.log_success(f"Updated config: {old_name} → {theme_name}")
    
    def log_reload_instructions(self) -> None:
        """Show instructions for reloading Atuin"""
        self.console.print(
            "[yellow]ℹ️  Atuin will use new theme on next invocation (Ctrl+R)[/yellow]"
        )
    
    def _generate_dynamic_theme(self, theme_data: dict) -> tuple[str, str]:
        """Generate TOML for dynamic theme
        
        Returns:
            (toml_content, theme_name) tuple
        """
        mat = get_material_colors(theme_data)
        
        toml_content = f"""# Atuin Theme - Dynamic (Material Design 3)
# Generated by theme system
# Colors extracted from wallpaper via matugen

[theme]
name = "dynamic"

[colors]
AlertInfo = "{mat.get("tertiary", "#a6e3a1")}"
AlertWarn = "{mat.get("secondary", "#fab387")}"
AlertError = "{mat.get("error", "#f38ba8")}"
Annotation = "{mat.get("primary", "#cba6f7")}"
Base = "{mat.get("on_surface", "#cdd6f4")}"
Guidance = "{mat.get("outline", "#9399b2")}"
Important = "{mat.get("error", "#f38ba8")}"
Title = "{mat.get("primary", "#cba6f7")}"
"""
        
        return toml_content, "dynamic"
    
    def _generate_static_theme(self, theme_data: dict) -> tuple[str, str]:
        """Generate TOML for static Catppuccin theme
        
        Returns:
            (toml_content, theme_name) tuple
        """
        ctp = get_catppuccin_colors(theme_data)
        variant = theme_data.get("theme", {}).get("name", "mocha")
        
        # Theme name matches existing static files: catppuccin-{variant}-mauve
        theme_name = f"catppuccin-{variant}-mauve"
        
        toml_content = f"""# Atuin Theme - Catppuccin {variant.title()} (Mauve accent)
# Generated by theme system
# Based on official Catppuccin color palette

[theme]
name = "{theme_name}"

[colors]
AlertInfo = "{ctp.get("green", "#a6e3a1")}"
AlertWarn = "{ctp.get("peach", "#fab387")}"
AlertError = "{ctp.get("red", "#f38ba8")}"
Annotation = "{ctp.get("mauve", "#cba6f7")}"
Base = "{ctp.get("text", "#cdd6f4")}"
Guidance = "{ctp.get("subtext0", "#9399b2")}"
Important = "{ctp.get("red", "#f38ba8")}"
Title = "{ctp.get("mauve", "#cba6f7")}"
"""
        
        return toml_content, theme_name
