"""btop theme generator"""

from pathlib import Path
from .base import BaseApp
from utils import get_material_colors, get_catppuccin_colors, is_dynamic_theme


class BtopTheme(BaseApp):
    """btop system monitor theme generator

    Generates a .theme file for btop's native theme system with 30+ color
    keys including gradient support for meters and graphs.

    Method: external_file
    Reload: SIGUSR2 signal
    """

    def __init__(self, config_home: Path):
        super().__init__("btop", config_home)
        self.themes_dir = config_home / "btop/themes"
        self.config_file = config_home / "btop/btop.conf"

    def apply_theme(self, theme_data: dict) -> None:
        """Apply theme to btop by generating theme file"""
        self.log_progress("Generating btop theme")

        # Generate theme content based on theme type
        if is_dynamic_theme(theme_data):
            content = self._generate_dynamic_theme(theme_data)
        else:
            content = self._generate_static_theme(theme_data)

        # Write theme file
        theme_file = self.themes_dir / "dynamic.theme"
        self.write_file(theme_file, content)

        # Reload btop if running
        self._reload_btop()

    def _generate_dynamic_theme(self, theme_data: dict) -> str:
        """Generate theme from Material Design 3 palette

        Maps MD3 semantic colors to btop's 30+ color keys with
        gradient support for temperature, CPU, memory, network,
        and process visualizations.
        """
        mat = get_material_colors(theme_data)

        return f'''# btop Theme - Dynamic (Material Design 3)
# Generated by theme system
# Colors extracted from wallpaper via matugen

# Main colors
theme[main_bg]=""
theme[main_fg]="{mat.get("on_surface", "#cdd6f4")}"
theme[title]="{mat.get("on_surface", "#cdd6f4")}"
theme[hi_fg]="{mat.get("primary", "#cba6f7")}"
theme[selected_bg]="{mat.get("surface_container_high", "#45475a")}"
theme[selected_fg]="{mat.get("primary", "#cba6f7")}"
theme[inactive_fg]="{mat.get("outline", "#7f849c")}"
theme[graph_text]="{mat.get("on_surface_variant", "#a6adc8")}"
theme[meter_bg]="{mat.get("surface_container", "#313244")}"
theme[proc_misc]="{mat.get("tertiary", "#a6e3a1")}"

# Box outline colors
theme[cpu_box]="{mat.get("primary", "#cba6f7")}"
theme[mem_box]="{mat.get("tertiary", "#a6e3a1")}"
theme[net_box]="{mat.get("secondary", "#f5c2e7")}"
theme[proc_box]="{mat.get("primary", "#89b4fa")}"
theme[div_line]="{mat.get("outline_variant", "#6c7086")}"

# Temperature gradient (green -> yellow -> red)
theme[temp_start]="{mat.get("tertiary", "#a6e3a1")}"
theme[temp_mid]="{mat.get("secondary", "#f9e2af")}"
theme[temp_end]="{mat.get("error", "#f38ba8")}"

# CPU gradient
theme[cpu_start]="{mat.get("primary_container", "#94e2d5")}"
theme[cpu_mid]="{mat.get("primary", "#89b4fa")}"
theme[cpu_end]="{mat.get("secondary", "#b4befe")}"

# Memory meters
theme[free_start]="{mat.get("primary", "#cba6f7")}"
theme[free_mid]="{mat.get("secondary", "#b4befe")}"
theme[free_end]="{mat.get("tertiary", "#89b4fa")}"

theme[cached_start]="{mat.get("tertiary_container", "#74c7ec")}"
theme[cached_mid]="{mat.get("tertiary", "#89b4fa")}"
theme[cached_end]="{mat.get("secondary", "#b4befe")}"

theme[available_start]="{mat.get("secondary", "#fab387")}"
theme[available_mid]="{mat.get("error_container", "#eba0ac")}"
theme[available_end]="{mat.get("error", "#f38ba8")}"

theme[used_start]="{mat.get("tertiary", "#a6e3a1")}"
theme[used_mid]="{mat.get("primary", "#94e2d5")}"
theme[used_end]="{mat.get("primary_container", "#89dceb")}"

# Network gradients
theme[download_start]="{mat.get("secondary", "#fab387")}"
theme[download_mid]="{mat.get("error_container", "#eba0ac")}"
theme[download_end]="{mat.get("error", "#f38ba8")}"

theme[upload_start]="{mat.get("tertiary", "#a6e3a1")}"
theme[upload_mid]="{mat.get("primary", "#94e2d5")}"
theme[upload_end]="{mat.get("primary_container", "#89dceb")}"

# Process gradient
theme[process_start]="{mat.get("primary_container", "#74c7ec")}"
theme[process_mid]="{mat.get("secondary", "#b4befe")}"
theme[process_end]="{mat.get("primary", "#cba6f7")}"
'''

    def _generate_static_theme(self, theme_data: dict) -> str:
        """Generate theme from Catppuccin palette

        Uses the standard Catppuccin color mapping with mauve as
        the primary accent color (user preference).
        """
        ctp = get_catppuccin_colors(theme_data)
        variant = theme_data.get("theme", {}).get("name", "mocha")

        return f'''# btop Theme - Catppuccin {variant.title()}
# Generated by theme system

# Main colors
theme[main_bg]=""
theme[main_fg]="{ctp.get("text", "#cdd6f4")}"
theme[title]="{ctp.get("text", "#cdd6f4")}"
theme[hi_fg]="{ctp.get("mauve", "#cba6f7")}"
theme[selected_bg]="{ctp.get("surface1", "#45475a")}"
theme[selected_fg]="{ctp.get("mauve", "#cba6f7")}"
theme[inactive_fg]="{ctp.get("overlay0", "#6c7086")}"
theme[graph_text]="{ctp.get("subtext0", "#a6adc8")}"
theme[meter_bg]="{ctp.get("surface0", "#313244")}"
theme[proc_misc]="{ctp.get("rosewater", "#f5e0dc")}"

# Box outline colors
theme[cpu_box]="{ctp.get("mauve", "#cba6f7")}"
theme[mem_box]="{ctp.get("green", "#a6e3a1")}"
theme[net_box]="{ctp.get("maroon", "#eba0ac")}"
theme[proc_box]="{ctp.get("blue", "#89b4fa")}"
theme[div_line]="{ctp.get("surface1", "#45475a")}"

# Temperature gradient (green -> yellow -> red)
theme[temp_start]="{ctp.get("green", "#a6e3a1")}"
theme[temp_mid]="{ctp.get("yellow", "#f9e2af")}"
theme[temp_end]="{ctp.get("red", "#f38ba8")}"

# CPU gradient (cool colors)
theme[cpu_start]="{ctp.get("teal", "#94e2d5")}"
theme[cpu_mid]="{ctp.get("sky", "#89dceb")}"
theme[cpu_end]="{ctp.get("lavender", "#b4befe")}"

# Memory meters
theme[free_start]="{ctp.get("mauve", "#cba6f7")}"
theme[free_mid]="{ctp.get("lavender", "#b4befe")}"
theme[free_end]="{ctp.get("blue", "#89b4fa")}"

theme[cached_start]="{ctp.get("sky", "#89dceb")}"
theme[cached_mid]="{ctp.get("blue", "#89b4fa")}"
theme[cached_end]="{ctp.get("lavender", "#b4befe")}"

theme[available_start]="{ctp.get("peach", "#fab387")}"
theme[available_mid]="{ctp.get("maroon", "#eba0ac")}"
theme[available_end]="{ctp.get("red", "#f38ba8")}"

theme[used_start]="{ctp.get("green", "#a6e3a1")}"
theme[used_mid]="{ctp.get("teal", "#94e2d5")}"
theme[used_end]="{ctp.get("sky", "#89dceb")}"

# Network gradients
theme[download_start]="{ctp.get("peach", "#fab387")}"
theme[download_mid]="{ctp.get("maroon", "#eba0ac")}"
theme[download_end]="{ctp.get("red", "#f38ba8")}"

theme[upload_start]="{ctp.get("green", "#a6e3a1")}"
theme[upload_mid]="{ctp.get("teal", "#94e2d5")}"
theme[upload_end]="{ctp.get("sky", "#89dceb")}"

# Process gradient
theme[process_start]="{ctp.get("sky", "#89dceb")}"
theme[process_mid]="{ctp.get("lavender", "#b4befe")}"
theme[process_end]="{ctp.get("mauve", "#cba6f7")}"
'''

    def _reload_btop(self) -> None:
        """Reload btop using SIGUSR2 signal

        Note: SIGUSR2 can crash if sent within ~8 seconds of btop startup.
        Using silent_fail to handle case where btop isn't running.
        """
        success = self.run_command(
            ["pkill", "-USR2", "btop"],
            error_msg="Could not reload btop (not running?)",
            silent_fail=True,
        )

        if success:
            self.log_success("Reloaded btop")
