"""btop theme generator"""

from pathlib import Path
from .base import BaseApp
from utils import get_material_colors, get_catppuccin_colors, is_dynamic_theme


class BtopTheme(BaseApp):
    """btop system monitor theme generator

    Generates a .theme file for btop's native theme system with 30+ color
    keys including gradient support for meters and graphs.

    Method: external_file
    Reload: SIGUSR2 signal
    """

    def __init__(self, config_home: Path):
        super().__init__("btop", config_home)
        self.themes_dir = config_home / "btop/themes"
        self.config_file = config_home / "btop/btop.conf"

    def apply_theme(self, theme_data: dict) -> None:
        """Apply theme to btop by generating theme file"""
        self.log_progress("Generating btop theme")

        # Generate theme content based on theme type
        if is_dynamic_theme(theme_data):
            content = self._generate_dynamic_theme(theme_data)
        else:
            content = self._generate_static_theme(theme_data)

        # Write theme file
        theme_file = self.themes_dir / "dynamic.theme"
        self.write_file(theme_file, content)

        # Reload btop if running
        self._reload_btop()

    def _generate_dynamic_theme(self, theme_data: dict) -> str:
        """Generate theme from Material Design 3 palette

        Maps MD3 semantic colors to btop's 30+ color keys with
        gradient support for temperature, CPU, memory, network,
        and process visualizations.
        """
        mat = get_material_colors(theme_data)

        return f'''# btop Theme - Dynamic (Material Design 3)
# Generated by theme system
# Mapping mirrors the previous ML4W matugen btop template.

# Main background, empty for terminal default / transparency
theme[main_bg]=""

# Main text color
theme[main_fg]="{mat.get("on_surface", "#cdd6f4")}"

# Title color for boxes
theme[title]="{mat.get("primary", "#cba6f7")}"

# Highlight color for keyboard shortcuts
theme[hi_fg]="{mat.get("secondary", "#89b4fa")}"

# Selected item in processes box
theme[selected_bg]="{mat.get("primary", "#cba6f7")}"
theme[selected_fg]="{mat.get("on_primary", "#11111b")}"

# Inactive/disabled text
theme[inactive_fg]="{mat.get("on_surface_variant", "#bac2de")}"

# Misc process box colors (mini cpu graphs, details)
theme[proc_misc]="{mat.get("tertiary", "#a6e3a1")}"

# Box outline colors (uniform, subtle)
theme[cpu_box]="{mat.get("outline", "#6c7086")}"
theme[mem_box]="{mat.get("outline", "#6c7086")}"
theme[net_box]="{mat.get("outline", "#6c7086")}"
theme[proc_box]="{mat.get("outline", "#6c7086")}"
theme[div_line]="{mat.get("outline_variant", "#585b70")}"

# Temperature graph
theme[temp_start]="{mat.get("secondary", "#89b4fa")}"
theme[temp_mid]="{mat.get("primary", "#cba6f7")}"
theme[temp_end]="{mat.get("error", "#f38ba8")}"

# CPU graph
theme[cpu_start]="{mat.get("secondary", "#89b4fa")}"
theme[cpu_mid]="{mat.get("primary", "#cba6f7")}"
theme[cpu_end]="{mat.get("error", "#f38ba8")}"

# Mem/Disk free meter
theme[free_start]="{mat.get("secondary", "#89b4fa")}"
theme[free_mid]=""
theme[free_end]="{mat.get("secondary_container", "#313244")}"

# Mem/Disk cached meter
theme[cached_start]="{mat.get("tertiary", "#a6e3a1")}"
theme[cached_mid]=""
theme[cached_end]="{mat.get("tertiary_container", "#313244")}"

# Mem/Disk available meter
theme[available_start]="{mat.get("primary", "#cba6f7")}"
theme[available_mid]=""
theme[available_end]="{mat.get("primary_container", "#313244")}"

# Mem/Disk used meter
theme[used_start]="{mat.get("error", "#f38ba8")}"
theme[used_mid]=""
theme[used_end]="{mat.get("error_container", "#313244")}"

# Download graph
theme[download_start]="{mat.get("secondary", "#89b4fa")}"
theme[download_mid]="{mat.get("primary", "#cba6f7")}"
theme[download_end]="{mat.get("tertiary", "#a6e3a1")}"

# Upload graph
theme[upload_start]="{mat.get("secondary", "#89b4fa")}"
theme[upload_mid]="{mat.get("primary", "#cba6f7")}"
theme[upload_end]="{mat.get("tertiary", "#a6e3a1")}"
'''

    def _generate_static_theme(self, theme_data: dict) -> str:
        """Generate theme from Catppuccin palette

        Uses the standard Catppuccin color mapping with mauve as
        the primary accent color (user preference).
        """
        ctp = get_catppuccin_colors(theme_data)
        variant = theme_data.get("theme", {}).get("name", "mocha")

        return f'''# btop Theme - Catppuccin {variant.title()}
# Generated by theme system
# Mapping mirrors the previous ML4W matugen btop template.

# Main background, empty for terminal default / transparency
theme[main_bg]=""

# Main text color
theme[main_fg]="{ctp.get("text", "#cdd6f4")}"

# Title color for boxes
theme[title]="{ctp.get("mauve", "#cba6f7")}"

# Highlight color for keyboard shortcuts
theme[hi_fg]="{ctp.get("blue", "#89b4fa")}"

# Selected item in processes box
theme[selected_bg]="{ctp.get("mauve", "#cba6f7")}"
theme[selected_fg]="{ctp.get("crust", "#11111b")}"

# Inactive/disabled text
theme[inactive_fg]="{ctp.get("subtext1", "#bac2de")}"

# Misc process box colors (mini cpu graphs, details)
theme[proc_misc]="{ctp.get("green", "#a6e3a1")}"

# Box outline colors (uniform, subtle)
theme[cpu_box]="{ctp.get("overlay0", "#6c7086")}"
theme[mem_box]="{ctp.get("overlay0", "#6c7086")}"
theme[net_box]="{ctp.get("overlay0", "#6c7086")}"
theme[proc_box]="{ctp.get("overlay0", "#6c7086")}"
theme[div_line]="{ctp.get("surface2", "#585b70")}"

# Temperature graph
theme[temp_start]="{ctp.get("blue", "#89b4fa")}"
theme[temp_mid]="{ctp.get("mauve", "#cba6f7")}"
theme[temp_end]="{ctp.get("red", "#f38ba8")}"

# CPU graph
theme[cpu_start]="{ctp.get("blue", "#89b4fa")}"
theme[cpu_mid]="{ctp.get("mauve", "#cba6f7")}"
theme[cpu_end]="{ctp.get("red", "#f38ba8")}"

# Mem/Disk free meter
theme[free_start]="{ctp.get("blue", "#89b4fa")}"
theme[free_mid]=""
theme[free_end]="{ctp.get("surface0", "#313244")}"

# Mem/Disk cached meter
theme[cached_start]="{ctp.get("green", "#a6e3a1")}"
theme[cached_mid]=""
theme[cached_end]="{ctp.get("surface0", "#313244")}"

# Mem/Disk available meter
theme[available_start]="{ctp.get("mauve", "#cba6f7")}"
theme[available_mid]=""
theme[available_end]="{ctp.get("surface0", "#313244")}"

# Mem/Disk used meter
theme[used_start]="{ctp.get("red", "#f38ba8")}"
theme[used_mid]=""
theme[used_end]="{ctp.get("surface0", "#313244")}"

# Download graph
theme[download_start]="{ctp.get("blue", "#89b4fa")}"
theme[download_mid]="{ctp.get("mauve", "#cba6f7")}"
theme[download_end]="{ctp.get("green", "#a6e3a1")}"

# Upload graph
theme[upload_start]="{ctp.get("blue", "#89b4fa")}"
theme[upload_mid]="{ctp.get("mauve", "#cba6f7")}"
theme[upload_end]="{ctp.get("green", "#a6e3a1")}"
'''

    def _reload_btop(self) -> None:
        """Reload btop using SIGUSR2 signal

        Note: SIGUSR2 can crash if sent within ~8 seconds of btop startup.
        Using silent_fail to handle case where btop isn't running.
        """
        success = self.run_command(
            ["pkill", "-USR2", "btop"],
            error_msg="Could not reload btop (not running?)",
            silent_fail=True,
        )

        if success:
            self.log_success("Reloaded btop")
