"""CAVA theme generator"""

from pathlib import Path
from .base import BaseApp
from utils import get_material_colors, get_catppuccin_colors, is_dynamic_theme
from utils.color_math import blend_colors, hex_to_hsl, hsl_to_hex


class CavaTheme(BaseApp):
    """CAVA (Console-based Audio Visualizer) theme generator
    
    Generates an 8-color vertical gradient theme file for CAVA's spectrum
    visualizer. Colors transition from bottom (color 1) to top (color 8).
    
    Method: External theme file
    Reload: SIGUSR2 signal (color-only, no audio interruption)
    """
    
    def __init__(self, config_home: Path):
        super().__init__("cava", config_home)
        self.themes_dir = config_home / "cava/themes"
        self.config_file = config_home / "cava/config"
    
    def apply_theme(self, theme_data: dict) -> None:
        """Apply theme to CAVA by generating dynamic theme file"""
        
        self.log_progress("Generating CAVA theme")
        
        # Generate gradient colors based on theme type
        if is_dynamic_theme(theme_data):
            gradient_colors = self._generate_dynamic_gradient(theme_data)
        else:
            gradient_colors = self._generate_static_gradient(theme_data)
        
        # Write theme file
        self._write_theme_file(gradient_colors)
        
        # Reload CAVA if running
        self._reload_cava()
        
        self.log_success("Generated cava theme")
        self._log_reload_info()
    
    def _generate_dynamic_gradient(self, theme_data: dict) -> list[str]:
        """Generate 8-color gradient from Material Design 3 palette
        
        Strategy:
        - Bottom third (1-3): primary -> accent blend
        - Middle third (4-5): accent variations
        - Top third (6-8): accent -> bright blend
        
        Returns:
            List of 8 hex colors
        """
        mat = get_material_colors(theme_data)
        
        # Base colors for gradient
        primary = mat.get('primary', '#cba6f7')
        secondary = mat.get('secondary', '#f5c2e7')
        tertiary = mat.get('tertiary', '#a6e3a1')
        
        # Build 8-color gradient
        return self._create_gradient(primary, secondary, tertiary)
    
    def _generate_static_gradient(self, theme_data: dict) -> list[str]:
        """Generate 8-color gradient from Catppuccin palette
        
        Uses mauve (primary), pink (secondary), and green (accent) for
        a visually appealing spectrum gradient.
        
        Returns:
            List of 8 hex colors
        """
        ctp = get_catppuccin_colors(theme_data)
        
        # Base colors for gradient
        primary = ctp.get('mauve', '#cba6f7')
        secondary = ctp.get('pink', '#f5c2e7')
        tertiary = ctp.get('green', '#a6e3a1')
        
        # Build 8-color gradient
        return self._create_gradient(primary, secondary, tertiary)
    
    def _create_gradient(self, base: str, mid: str, top: str) -> list[str]:
        """Create smooth 8-color gradient from three base colors
        
        Blends through color space to create visually smooth transitions.
        
        Args:
            base: Bottom color (darkest)
            mid: Middle color
            top: Top color (brightest)
            
        Returns:
            List of 8 hex colors with '#' prefix
        """
        gradient = []
        
        # Bottom third (1-3): base -> mid
        gradient.append(base)
        gradient.append(blend_colors(base, mid, 0.33))
        gradient.append(blend_colors(base, mid, 0.66))
        
        # Middle third (4-5): mid variations
        gradient.append(mid)
        gradient.append(blend_colors(mid, top, 0.33))
        
        # Top third (6-8): mid -> top with extra brightness at peak
        gradient.append(blend_colors(mid, top, 0.66))
        gradient.append(top)
        
        # Extra bright at peak (15% lighter)
        h, s, l = hex_to_hsl(top)
        peak_lightness = min(100, l * 1.15)
        gradient.append(hsl_to_hex((h, s, peak_lightness)))
        
        return gradient
    
    def _write_theme_file(self, gradient_colors: list[str]) -> None:
        """Write theme file to ~/.config/cava/themes/dynamic
        
        Args:
            gradient_colors: List of 8 hex colors
        """
        content = "[color]\n"
        content += "# Dynamic theme generated by theme-system\n"
        content += "# Auto-reloaded via SIGUSR2 signal when theme changes\n"
        content += "# Vertical gradient: bottom (color_1) -> top (color_8)\n"
        content += "\n"
        content += "gradient = 1\n"
        
        for i, color in enumerate(gradient_colors, start=1):
            content += f"gradient_color_{i} = '{color}'\n"
        
        # Write to themes directory
        theme_file = self.themes_dir / "dynamic"
        self.write_file(theme_file, content)
    
    def _reload_cava(self) -> None:
        """Reload CAVA colors using SIGUSR2 signal
        
        SIGUSR2 triggers color-only reload without reinitializing
        audio processing or resetting bar heights.
        """
        success = self.run_command(
            ['pkill', '-USR2', 'cava'],
            error_msg="Could not reload cava (not running?)",
            silent_fail=True
        )
        
        if success:
            self.log_success("Reloaded cava colors")
    
    def _log_reload_info(self) -> None:
        """Show reload information for CAVA"""
        self.console.print(
            "[dim]  Reload: Auto-reloaded if running, or press 'c' in cava[/dim]"
        )
