"""Ghostty terminal emulator theme integration"""

from pathlib import Path
from .base import BaseApp
from utils import get_material_colors, is_dynamic_theme, get_theme_variant


class GhosttyTheme(BaseApp):
    """Ghostty terminal emulator theme integration

    Method: hybrid (builtin for static, external_file for dynamic)
    Reload: manual (keybind Cmd+Shift+, on macOS, Ctrl+Shift+, on Linux)

    Static themes: Update theme directive to Catppuccin variant
    Dynamic themes: Generate colors-ghostty.conf with MD3 colors
    """

    # GUI-only app - skip on headless systems
    requires_gui = True

    def __init__(self, config_home: Path):
        super().__init__("Ghostty", config_home)
        self.config_file = config_home / "ghostty/config"
        self.colors_file = config_home / "ghostty/colors-ghostty.conf"

    def apply_theme(self, theme_data: dict) -> None:
        """Apply theme to Ghostty"""
        if not self.config_file.exists():
            self.log_warning(f"Ghostty config not found: {self.config_file}")
            return

        self.log_progress("Updating Ghostty theme")

        if is_dynamic_theme(theme_data):
            self._generate_dynamic_colors(theme_data)
            self._update_config_for_dynamic()
        else:
            variant = theme_data.get("theme", {}).get("name", "mocha")
            self._update_config_for_static(variant)

        self._apply_opacity(theme_data)
        self.log_warning("Reload Ghostty: Cmd+Shift+, (macOS) or Ctrl+Shift+, (Linux)")

    def _generate_dynamic_colors(self, theme_data: dict) -> None:
        """Generate colors-ghostty.conf from Material Design 3 colors"""
        mat = get_material_colors(theme_data)
        variant = get_theme_variant(theme_data)

        if variant == "light":
            ansi = self._get_light_ansi(mat)
        else:
            ansi = self._get_dark_ansi(mat)

        content = f"""# Ghostty Colors - Dynamic Theme
# Generated by theme system from wallpaper (Material Design 3)
# Mode: {variant}

# Basic colors
foreground = {mat.get("on_surface", "#cdd6f4")}
background = {mat.get("background", "#1e1e2e")}

# Cursor
cursor-color = {mat.get("primary", "#cba6f7")}
cursor-text = {mat.get("on_primary", "#11111b")}

# Selection
selection-foreground = {mat.get("on_primary_container", "#cdd6f4")}
selection-background = {mat.get("primary_container", "#45475a")}

# ANSI colors (16-color palette)
{ansi}
"""
        self.write_file(self.colors_file, content)

    def _get_dark_ansi(self, mat: dict) -> str:
        """Generate ANSI palette for dark mode"""
        return f"""palette = 0={mat.get("outline", "#45475a")}
palette = 1={mat.get("error", "#f38ba8")}
palette = 2={mat.get("tertiary", "#a6e3a1")}
palette = 3={mat.get("secondary", "#f9e2af")}
palette = 4={mat.get("primary", "#89b4fa")}
palette = 5={mat.get("primary", "#cba6f7")}
palette = 6={mat.get("tertiary", "#94e2d5")}
palette = 7={mat.get("on_surface", "#bac2de")}
palette = 8={mat.get("surface_container", "#585b70")}
palette = 9={mat.get("error", "#f38ba8")}
palette = 10={mat.get("tertiary", "#a6e3a1")}
palette = 11={mat.get("secondary", "#f9e2af")}
palette = 12={mat.get("primary", "#89b4fa")}
palette = 13={mat.get("primary", "#cba6f7")}
palette = 14={mat.get("tertiary", "#94e2d5")}
palette = 15={mat.get("on_surface_variant", "#a6adc8")}"""

    def _get_light_ansi(self, mat: dict) -> str:
        """Generate ANSI palette for light mode"""
        return f"""palette = 0={mat.get("surface_container_high", "#45475a")}
palette = 1={mat.get("error", "#d20f39")}
palette = 2={mat.get("tertiary", "#40a02b")}
palette = 3={mat.get("secondary", "#df8e1d")}
palette = 4={mat.get("primary", "#1e66f5")}
palette = 5={mat.get("primary", "#8839ef")}
palette = 6={mat.get("tertiary", "#179299")}
palette = 7={mat.get("on_surface", "#4c4f69")}
palette = 8={mat.get("outline", "#6c6f85")}
palette = 9={mat.get("error", "#d20f39")}
palette = 10={mat.get("tertiary", "#40a02b")}
palette = 11={mat.get("secondary", "#df8e1d")}
palette = 12={mat.get("primary", "#1e66f5")}
palette = 13={mat.get("primary", "#8839ef")}
palette = 14={mat.get("tertiary", "#179299")}
palette = 15={mat.get("on_surface_variant", "#5c5f77")}"""

    def _update_config_for_dynamic(self) -> None:
        """Update config for dynamic theme: add config-file, comment out theme"""
        if not self.config_file.exists():
            return

        content = self.config_file.read_text()
        lines = content.split("\n")
        new_lines = []
        has_config_file = False

        for line in lines:
            stripped = line.strip()

            # Comment out theme directive for dynamic
            if (
                stripped.startswith("theme")
                and "=" in stripped
                and not stripped.startswith("#")
            ):
                new_lines.append(f"# {line}  # Disabled for dynamic theme")
                continue

            # Check for existing colors config-file directive
            if stripped.startswith("config-file") and "colors-ghostty" in stripped:
                # Uncomment if commented
                if stripped.startswith("#"):
                    new_lines.append("config-file = colors-ghostty.conf")
                else:
                    new_lines.append(line)
                has_config_file = True
                continue

            new_lines.append(line)

        # Add config-file directive if not present
        if not has_config_file:
            # Insert after initial comments
            insert_idx = 0
            for i, line in enumerate(new_lines):
                if line.strip() and not line.strip().startswith("#"):
                    insert_idx = i
                    break
            new_lines.insert(insert_idx, "config-file = colors-ghostty.conf")
            new_lines.insert(insert_idx + 1, "")

        self.config_file.write_text("\n".join(new_lines))
        self.log_success("Updated Ghostty for dynamic theme")

    def _update_config_for_static(self, variant: str) -> None:
        """Update config for static theme: set theme, comment out config-file"""
        if not self.config_file.exists():
            return

        theme_name = f"Catppuccin {variant.title()}"
        content = self.config_file.read_text()
        lines = content.split("\n")
        new_lines = []
        has_theme = False

        for line in lines:
            stripped = line.strip()

            # Handle theme directive
            if (
                "theme" in stripped
                and "=" in stripped
                and "config-file" not in stripped
            ):
                if stripped.startswith("#") and "Disabled for dynamic" in line:
                    # Uncomment and update
                    new_lines.append(f"theme = {theme_name}")
                elif stripped.startswith("#"):
                    # Other commented theme line - uncomment
                    new_lines.append(f"theme = {theme_name}")
                else:
                    # Update existing
                    new_lines.append(f"theme = {theme_name}")
                has_theme = True
                continue

            # Comment out config-file for colors (not needed for static)
            if stripped.startswith("config-file") and "colors-ghostty" in stripped:
                if not stripped.startswith("#"):
                    new_lines.append(f"# {line}  # Disabled for static theme")
                else:
                    new_lines.append(line)
                continue

            new_lines.append(line)

        # Add theme directive if not present
        if not has_theme:
            insert_idx = 0
            for i, line in enumerate(new_lines):
                if line.strip() and not line.strip().startswith("#"):
                    insert_idx = i
                    break
            new_lines.insert(insert_idx, f"theme = {theme_name}")
            new_lines.insert(insert_idx + 1, "")

        self.config_file.write_text("\n".join(new_lines))
        self.log_success(f'Updated Ghostty: theme = "{theme_name}"')

    def _apply_opacity(self, theme_data: dict) -> None:
        """Apply opacity settings to config"""
        theme = theme_data.get("theme", {})
        opacity_percent = theme.get("opacity", 0)

        if not self.config_file.exists():
            return

        content = self.config_file.read_text()
        lines = content.split("\n")
        new_lines = []
        has_opacity = False
        has_blur = False

        for line in lines:
            stripped = line.strip()

            # Update background-opacity
            if "background-opacity" in stripped:
                if opacity_percent > 0:
                    opacity_value = opacity_percent / 100.0
                    new_lines.append(f"background-opacity = {opacity_value:.2f}")
                else:
                    new_lines.append("# background-opacity = 1.0")
                has_opacity = True
                continue

            # Update background-blur
            if "background-blur" in stripped:
                if opacity_percent > 0:
                    new_lines.append("background-blur = 20")
                else:
                    new_lines.append("# background-blur = 20")
                has_blur = True
                continue

            new_lines.append(line)

        # Add opacity settings if not present and needed
        if opacity_percent > 0:
            opacity_value = opacity_percent / 100.0
            if not has_opacity:
                new_lines.append("")
                new_lines.append("# Transparency")
                new_lines.append(f"background-opacity = {opacity_value:.2f}")
            if not has_blur:
                new_lines.append("background-blur = 20")

        self.config_file.write_text("\n".join(new_lines))
