"""gitui theme generator"""

from pathlib import Path
from .base import BaseApp
from utils import get_material_colors, get_catppuccin_colors, is_dynamic_theme


class GituiTheme(BaseApp):
    """gitui (blazingly fast terminal UI for git) theme generator

    Generates complete theme.ron file with all 21 color keys.
    RON format requires string templating (no Python RON library).

    Method: external_file (generate complete theme.ron)
    Reload: Manual (quit and restart gitui)
    """

    def __init__(self, config_home: Path):
        super().__init__("gitui", config_home)
        self.theme_file = config_home / "gitui/theme.ron"

    def apply_theme(self, theme_data: dict) -> None:
        """Apply theme to gitui by generating theme.ron"""
        self.log_progress("Generating gitui theme")

        # Generate theme colors based on theme type
        if is_dynamic_theme(theme_data):
            colors = self._generate_dynamic_colors(theme_data)
        else:
            colors = self._generate_static_colors(theme_data)

        # Generate RON content
        ron_content = self._format_ron(colors)

        # Write theme file
        self.write_file(self.theme_file, ron_content)

    def _generate_dynamic_colors(self, theme_data: dict) -> dict:
        """Generate colors from Material Design 3 palette

        Maps MD3 semantic colors to gitui's 21 theme keys.

        Returns:
            Dictionary of gitui theme keys -> hex color values
        """
        mat = get_material_colors(theme_data)

        return {
            "selected_tab": "Reset",
            "command_fg": mat.get("on_surface", "#cdd6f4"),
            "selection_bg": mat.get("surface_container_high", "#585b70"),
            "selection_fg": mat.get("on_surface", "#cdd6f4"),
            "cmdbar_bg": mat.get("surface_container", "#181825"),
            "cmdbar_extra_lines_bg": mat.get("surface_container", "#181825"),
            "disabled_fg": mat.get("outline", "#7f849c"),
            "diff_line_add": mat.get("tertiary", "#a6e3a1"),
            "diff_line_delete": mat.get("error", "#f38ba8"),
            "diff_file_added": mat.get("tertiary", "#a6e3a1"),
            "diff_file_removed": mat.get("error", "#eba0ac"),
            "diff_file_moved": mat.get("primary", "#cba6f7"),
            "diff_file_modified": mat.get("secondary", "#fab387"),
            "commit_hash": mat.get("primary", "#b4befe"),
            "commit_time": mat.get("on_surface_variant", "#bac2de"),
            "commit_author": mat.get("tertiary", "#74c7ec"),
            "danger_fg": mat.get("error", "#f38ba8"),
            "push_gauge_bg": mat.get("primary", "#89b4fa"),
            "push_gauge_fg": mat.get("on_primary", "#1e1e2e"),
            "tag_fg": mat.get("secondary", "#f5e0dc"),
            "branch_fg": mat.get("tertiary", "#94e2d5"),
        }

    def _generate_static_colors(self, theme_data: dict) -> dict:
        """Generate colors from Catppuccin palette

        Based on official Catppuccin gitui themes.
        https://github.com/catppuccin/gitui

        Returns:
            Dictionary of gitui theme keys -> hex color values
        """
        ctp = get_catppuccin_colors(theme_data)

        return {
            "selected_tab": "Reset",
            "command_fg": ctp.get("text", "#cdd6f4"),
            "selection_bg": ctp.get("surface2", "#585b70"),
            "selection_fg": ctp.get("text", "#cdd6f4"),
            "cmdbar_bg": ctp.get("mantle", "#181825"),
            "cmdbar_extra_lines_bg": ctp.get("mantle", "#181825"),
            "disabled_fg": ctp.get("overlay0", "#7f849c"),
            "diff_line_add": ctp.get("green", "#a6e3a1"),
            "diff_line_delete": ctp.get("red", "#f38ba8"),
            "diff_file_added": ctp.get("green", "#a6e3a1"),
            "diff_file_removed": ctp.get("maroon", "#eba0ac"),
            "diff_file_moved": ctp.get("mauve", "#cba6f7"),
            "diff_file_modified": ctp.get("peach", "#fab387"),
            "commit_hash": ctp.get("lavender", "#b4befe"),
            "commit_time": ctp.get("subtext1", "#bac2de"),
            "commit_author": ctp.get("sapphire", "#74c7ec"),
            "danger_fg": ctp.get("red", "#f38ba8"),
            "push_gauge_bg": ctp.get("blue", "#89b4fa"),
            "push_gauge_fg": ctp.get("crust", "#1e1e2e"),
            "tag_fg": ctp.get("rosewater", "#f5e0dc"),
            "branch_fg": ctp.get("teal", "#94e2d5"),
        }

    def _format_ron(self, colors: dict) -> str:
        """Format colors as RON (Rusty Object Notation)

        RON format for gitui theme:
        - Values wrapped in Some() for partial override support
        - "Reset" is special - inherits terminal default
        - All other values are hex colors

        Returns:
            RON formatted string
        """
        lines = [
            "// gitui theme - Generated by theme-system",
            "// Do not edit manually - run 'theme set <name>' to change",
            "(",
        ]

        for key, value in colors.items():
            if value == "Reset":
                lines.append(f'    {key}: Some("Reset"),')
            else:
                lines.append(f'    {key}: Some("{value}"),')

        lines.append(")")

        return "\n".join(lines) + "\n"
