"""Hyprland theme integration."""

from pathlib import Path

from .base import BaseApp
from utils import get_material_colors


class HyprlandTheme(BaseApp):
    """Generate Hyprland Lua colors from Material Design 3 theme data."""

    requires_gui = True
    supported_platforms = ("linux",)

    def __init__(self, config_home: Path):
        super().__init__("Hyprland", config_home)
        self.colors_file = config_home / "hypr/colors.lua"

    def apply_theme(self, theme_data: dict) -> None:
        mat = get_material_colors(theme_data)

        self.log_progress("Updating Hyprland colors")
        self.write_file(self.colors_file, self._render_colors(mat))
        self._reload_hyprland()

    def _render_colors(self, mat: dict) -> str:
        keys = [
            "background",
            "error",
            "error_container",
            "inverse_on_surface",
            "inverse_primary",
            "inverse_surface",
            "on_background",
            "on_error",
            "on_error_container",
            "on_primary",
            "on_primary_container",
            "on_primary_fixed",
            "on_primary_fixed_variant",
            "on_secondary",
            "on_secondary_container",
            "on_secondary_fixed",
            "on_secondary_fixed_variant",
            "on_surface",
            "on_surface_variant",
            "on_tertiary",
            "on_tertiary_container",
            "on_tertiary_fixed",
            "on_tertiary_fixed_variant",
            "outline",
            "outline_variant",
            "primary",
            "primary_container",
            "primary_fixed",
            "primary_fixed_dim",
            "scrim",
            "secondary",
            "secondary_container",
            "secondary_fixed",
            "secondary_fixed_dim",
            "shadow",
            "source_color",
            "surface",
            "surface_bright",
            "surface_container",
            "surface_container_high",
            "surface_container_highest",
            "surface_container_low",
            "surface_container_lowest",
            "surface_dim",
            "surface_tint",
            "surface_variant",
            "tertiary",
            "tertiary_container",
            "tertiary_fixed",
            "tertiary_fixed_dim",
        ]

        lines = [
            "-- Hyprland colors - generated by theme-system",
            "-- Do not edit directly.",
            "",
        ]

        for key in keys:
            value = mat.get(key)
            if not value:
                continue
            lines.append(f'{key} = "{self._hypr_rgba(value)}"')

        return "\n".join(lines) + "\n"

    def _hypr_rgba(self, color: str) -> str:
        hex_color = color.strip().lstrip("#")
        if len(hex_color) == 6:
            hex_color = f"{hex_color}ff"
        if len(hex_color) != 8:
            raise ValueError(f"Unsupported Hyprland color: {color}")
        return f"rgba({hex_color.lower()})"

    def _reload_hyprland(self) -> None:
        if not self.command_exists("hyprctl"):
            self.log_warning("hyprctl not found; install Hyprland before applying Hyprland theme")
            return

        if self.run_command(["hyprctl", "reload"], error_msg="Hyprland reload failed"):
            self.log_success("Reloaded Hyprland")
