"""hyprlock screen-locker theme integration."""

import os
import subprocess
from pathlib import Path

import yaml

from .base import BaseApp
from utils import get_material_colors


def _chezmoi_source() -> Path:
    """Resolve the chezmoi source dir (for the shared wallpaper state)."""
    try:
        result = subprocess.run(
            ["chezmoi", "source-path"], capture_output=True, text=True, timeout=5
        )
        if result.returncode == 0:
            source = Path(result.stdout.strip())
            if source.exists():
                return source
    except (subprocess.TimeoutExpired, FileNotFoundError):
        pass

    xdg_data = os.environ.get("XDG_DATA_HOME", str(Path.home() / ".local/share"))
    return Path(xdg_data) / "chezmoi"


def _rgb(hex_color: str) -> str:
    """#RRGGBB -> hyprlang rgb(RRGGBB)."""
    return "rgb(" + hex_color.lstrip("#") + ")"


class HyprlockTheme(BaseApp):
    """Theme the hyprlock screen locker from the Material Design 3 palette.

    Writes (both consumed by ~/.config/hypr/hyprlock.conf):
      - hyprlock-colors.conf : hyprlang `$primary = rgb(...)` color variables
      - hyprlock-bg.png      : the current wallpaper, heavily blurred and fully
                               opaque (diffusion, no transparency)

    hyprlock reads both on the next lock, so there's nothing to reload.
    """

    requires_gui = True
    supported_platforms = ("linux",)
    wallpaper_derived = True

    COLOR_KEYS = [
        "primary",
        "on_primary",
        "secondary",
        "tertiary",
        "on_surface",
        "on_surface_variant",
        "surface",
        "surface_container",
        "error",
    ]

    def __init__(self, config_home: Path):
        super().__init__("hyprlock", config_home)
        self.colors_file = config_home / "hypr/hyprlock-colors.conf"
        self.background_file = config_home / "hypr/hyprlock-bg.png"

    def apply_theme(self, theme_data: dict) -> None:
        mat = get_material_colors(theme_data)

        self.log_progress("Updating hyprlock colors")
        lines = ["# Generated by theme-system — sourced by hyprlock.conf"]
        for key in self.COLOR_KEYS:
            if key in mat:
                lines.append(f"${key} = {_rgb(mat[key])}")
        self.write_file(self.colors_file, "\n".join(lines) + "\n")

        self._render_background(theme_data)

    def _render_background(self, theme_data: dict) -> None:
        wallpaper = self._current_wallpaper(theme_data)
        if not wallpaper:
            self.log_warning("No current wallpaper; skipping hyprlock background")
            return
        if not self.command_exists("magick"):
            self.log_warning("ImageMagick not found; skipping hyprlock background")
            return

        self.background_file.parent.mkdir(parents=True, exist_ok=True)
        # Heavy gaussian blur (diffusion), fully opaque — no alpha, no opacity.
        self.run_command(
            [
                "magick",
                str(wallpaper),
                "-resize", "2560x1440^",
                "-gravity", "center",
                "-extent", "2560x1440",
                "-blur", "0x32",
                str(self.background_file),
            ],
            error_msg="hyprlock background render failed",
            silent_fail=True,
            timeout=30,
        )

    def _current_wallpaper(self, theme_data: dict) -> str | None:
        wp = theme_data.get("theme", {}).get("source_wallpaper")
        if wp and Path(wp).exists():
            return wp

        state_file = _chezmoi_source() / ".chezmoidata/wallpaper-state.yaml"
        if not state_file.exists():
            return None
        try:
            data = yaml.safe_load(state_file.read_text()) or {}
        except yaml.YAMLError:
            return None
        wp = data.get("wallpaper", {}).get("current")
        return wp if wp and Path(wp).exists() else None
