"""Posting HTTP client theme generator"""

from pathlib import Path
from .base import BaseApp
from utils import get_material_colors, get_catppuccin_colors, is_dynamic_theme


class PostingTheme(BaseApp):
    """Posting theme generator

    Method: external_file (generates theme YAML in ~/.local/share/posting/themes/)
    Reload: Automatic - posting watches theme files by default

    Note: Posting does NOT support transparent backgrounds due to Textual
    framework limitations. Background colors match the terminal theme's
    base color for visual cohesion.
    """

    def __init__(self, config_home: Path):
        super().__init__("Posting", config_home)
        # Theme files go to XDG_DATA_HOME, not XDG_CONFIG_HOME
        self.data_home = Path.home() / ".local/share"
        self.themes_dir = self.data_home / "posting/themes"
        self.config_file = config_home / "posting/config.yaml"

    def apply_theme(self, theme_data: dict) -> None:
        """Apply theme to Posting"""
        self.log_progress("Updating Posting theme")

        if is_dynamic_theme(theme_data):
            self._generate_dynamic_theme(theme_data)
            theme_name = "dynamic"
        else:
            theme_name = self._generate_static_theme(theme_data)

        self._update_config(theme_name)
        self.log_success(f"Posting theme: {theme_name}")

    def _generate_dynamic_theme(self, theme_data: dict) -> None:
        """Generate dynamic.yaml from Material Design 3 colors

        Background uses MD3 background color (matches terminal).
        """
        mat = get_material_colors(theme_data)
        variant = theme_data.get("theme", {}).get("variant", "dark")
        is_dark = variant != "light"

        # Use explicit background color (transparency not supported by Textual)
        bg = mat.get("background", "#1e1e2e")
        surface = mat.get("surface_container", "#313244")

        content = f'''# Posting Dynamic Theme
# Generated by theme system from wallpaper (Material Design 3)
# Background matches terminal for visual cohesion (transparency not supported)

name: dynamic
primary: "{mat.get("primary", "#cba6f7")}"
secondary: "{mat.get("secondary", "#89b4fa")}"
accent: "{mat.get("tertiary", "#a6e3a1")}"
background: "{bg}"
surface: "{surface}"
error: "{mat.get("error", "#f38ba8")}"
success: "{mat.get("tertiary", "#a6e3a1")}"
warning: "{mat.get("secondary", "#f9e2af")}"
dark: {str(is_dark).lower()}

text_area:
  cursor: "reverse {mat.get("on_surface", "#cdd6f4")}"
  cursor_line: "underline {mat.get("on_surface", "#cdd6f4")}"
  selection: "reverse {mat.get("outline", "#6c7086")}"
  gutter: "bold {mat.get("tertiary", "#a6e3a1")}"
  matched_bracket: "reverse {mat.get("on_surface_variant", "#9399b2")}"

url:
  base: "italic {mat.get("primary", "#89b4fa")}"
  protocol: "bold {mat.get("secondary", "#94e2d5")}"
  separator: "{mat.get("on_surface", "#cdd6f4")}"

syntax:
  json_key: "italic {mat.get("primary", "#89b4fa")}"
  json_number: "{mat.get("tertiary", "#fab387")}"
  json_string: "{mat.get("tertiary", "#a6e3a1")}"
  json_boolean: "{mat.get("secondary", "#89dceb")}"
  json_null: "{mat.get("outline", "#6c7086")}"

method:
  get: "bold {mat.get("primary", "#89b4fa")}"
  post: "bold {mat.get("tertiary", "#a6e3a1")}"
  put: "bold {mat.get("secondary", "#f9e2af")}"
  delete: "bold {mat.get("error", "#f38ba8")}"
  patch: "bold {mat.get("secondary", "#94e2d5")}"
  options: "bold {mat.get("primary_container", "#b4befe")}"
  head: "bold {mat.get("primary", "#cba6f7")}"
'''

        self.themes_dir.mkdir(parents=True, exist_ok=True)
        self.write_file(self.themes_dir / "dynamic.yaml", content)

    def _generate_static_theme(self, theme_data: dict) -> str:
        """Generate Catppuccin theme from palette

        Background uses Catppuccin base color (matches terminal).

        Returns:
            Theme name to reference in config
        """
        ctp = get_catppuccin_colors(theme_data)
        variant = theme_data.get("theme", {}).get("name", "mocha")
        theme_name = f"catppuccin-{variant}-mauve"
        is_dark = variant != "latte"

        # Use explicit background color (transparency not supported by Textual)
        bg = ctp.get("base", "#1e1e2e")
        surface = ctp.get("surface0", "#313244")

        content = f'''# Catppuccin {variant.title()} for Posting
# Generated by theme system
# Background matches terminal for visual cohesion (transparency not supported)

name: {theme_name}
primary: "{ctp.get("mauve", "#cba6f7")}"
secondary: "{ctp.get("blue", "#89b4fa")}"
accent: "{ctp.get("green", "#a6e3a1")}"
background: "{bg}"
surface: "{surface}"
error: "{ctp.get("red", "#f38ba8")}"
success: "{ctp.get("green", "#a6e3a1")}"
warning: "{ctp.get("yellow", "#f9e2af")}"
dark: {str(is_dark).lower()}

text_area:
  cursor: "reverse {ctp.get("rosewater", "#f5e0dc")}"
  cursor_line: "underline {ctp.get("text", "#cdd6f4")}"
  selection: "reverse {ctp.get("overlay0", "#6c7086")}"
  gutter: "bold {ctp.get("green", "#a6e3a1")}"
  matched_bracket: "reverse {ctp.get("subtext1", "#9399b2")}"

url:
  base: "italic {ctp.get("blue", "#89b4fa")}"
  protocol: "bold {ctp.get("teal", "#94e2d5")}"
  separator: "{ctp.get("text", "#cdd6f4")}"

syntax:
  json_key: "italic {ctp.get("blue", "#89b4fa")}"
  json_number: "{ctp.get("peach", "#fab387")}"
  json_string: "{ctp.get("green", "#a6e3a1")}"
  json_boolean: "{ctp.get("sky", "#89dceb")}"
  json_null: "{ctp.get("overlay0", "#6c7086")}"

method:
  get: "bold {ctp.get("blue", "#89b4fa")}"
  post: "bold {ctp.get("green", "#a6e3a1")}"
  put: "bold {ctp.get("yellow", "#f9e2af")}"
  delete: "bold {ctp.get("red", "#f38ba8")}"
  patch: "bold {ctp.get("teal", "#94e2d5")}"
  options: "bold {ctp.get("lavender", "#b4befe")}"
  head: "bold {ctp.get("mauve", "#cba6f7")}"
'''

        self.themes_dir.mkdir(parents=True, exist_ok=True)
        self.write_file(self.themes_dir / f"{theme_name}.yaml", content)
        return theme_name

    def _update_config(self, theme_name: str) -> None:
        """Update config.yaml with theme reference"""
        if not self.config_file.exists():
            # Create minimal config
            content = f"""theme: {theme_name}
watch_themes: true
load_user_themes: true
"""
            self.config_file.parent.mkdir(parents=True, exist_ok=True)
            self.write_file(self.config_file, content)
            return

        try:
            from ruamel.yaml import YAML

            yaml = YAML()
            yaml.preserve_quotes = True

            with open(self.config_file, "r") as f:
                config = yaml.load(f) or {}

            config["theme"] = theme_name

            with open(self.config_file, "w") as f:
                yaml.dump(config, f)

        except ImportError:
            # Fallback: simple regex replacement
            import re

            with open(self.config_file, "r") as f:
                content = f.read()

            if "theme:" in content:
                content = re.sub(
                    r"^theme:.*$", f"theme: {theme_name}", content, flags=re.MULTILINE
                )
            else:
                content = f"theme: {theme_name}\n" + content

            with open(self.config_file, "w") as f:
                f.write(content)
