"""SketchyBar theme generator"""

from pathlib import Path
from .base import BaseApp
from utils import (
    hex_to_argb,
    get_material_colors,
    get_catppuccin_colors,
    is_dynamic_theme,
    opacity_to_alpha,
)


class SketchybarTheme(BaseApp):
    """SketchyBar macOS menu bar replacement theme generator

    Generates:
    - colors-sketchybar.sh: Color variables in ARGB format with helper function
    - opacity-sketchybar.sh: Opacity settings and add_opacity() helper

    SketchyBar must be explicitly reloaded via --reload command.
    """

    # GUI-only app - skip on headless systems (macOS-only anyway)
    requires_gui = True

    def __init__(self, config_home: Path):
        super().__init__("SketchyBar", config_home)
        self.colors_file = config_home / "sketchybar/colors-sketchybar.sh"
        self.opacity_file = config_home / "sketchybar/opacity-sketchybar.sh"

    def apply_theme(self, theme_data: dict) -> None:
        """Apply theme to SketchyBar"""
        self.generate_colors(theme_data)
        self.generate_opacity(theme_data)
        self.reload()

    def generate_colors(self, theme_data: dict) -> None:
        """Generate colors-sketchybar.sh with ARGB color exports"""
        self.log_progress("Generating Sketchybar colors")

        if is_dynamic_theme(theme_data):
            content = self._generate_dynamic_colors(theme_data)
        else:
            content = self._generate_static_colors(theme_data)

        self.write_file(self.colors_file, content, executable=True)

    def generate_opacity(self, theme_data: dict) -> None:
        """Generate opacity-sketchybar.sh with opacity settings"""
        theme = theme_data.get("theme", {})
        opacity_percent = theme.get("opacity", 0)

        self.log_progress(
            f"Generating Sketchybar opacity ({opacity_percent}%)", emoji="🔲"
        )

        # Convert percentage to hex alpha (0-100 → 0x00-0xFF)
        alpha_hex = opacity_to_alpha(opacity_percent, format="hex").lstrip("0x")

        if opacity_percent > 0:
            content = f"""#!/bin/bash
# SketchyBar Opacity - {opacity_percent}%
# Generated by theme system

export OPACITY_ENABLED=true
export OPACITY_ALPHA="0x{alpha_hex}"
export BLUR_RADIUS=30

# Helper function to add opacity to ARGB colors
# Usage: add_opacity "0xff1e1e2e" → "0xa51e1e2e" (with current opacity)
add_opacity() {{
  local color="$1"
  # Strip 0xff prefix if present, or 0x prefix, or # prefix
  color="${{color#0xff}}"
  color="${{color#0x}}"
  color="${{color#\\#}}"
  # Return with opacity alpha
  echo "0x${{OPACITY_ALPHA#0x}}${{color}}"
}}
"""
        else:
            content = """#!/bin/bash
# SketchyBar Opacity - Disabled
# Generated by theme system

export OPACITY_ENABLED=false
export OPACITY_ALPHA="0xff"
export BLUR_RADIUS=0

# Helper function to add opacity to ARGB colors (no-op when opacity disabled)
add_opacity() {
  local color="$1"
  # Strip 0xff prefix if present, or 0x prefix, or # prefix
  color="${color#0xff}"
  color="${color#0x}"
  color="${color#\\#}"
  # Return fully opaque
  echo "0xff${color}"
}
"""

        self.write_file(self.opacity_file, content, executable=True)

    def reload(self) -> None:
        """Reload SketchyBar to apply new colors"""
        if not self.command_exists("sketchybar"):
            self.log_warning("Sketchybar not found (not running?)")
            return

        success = self.run_command(
            ["sketchybar", "--reload"], error_msg="Sketchybar reload failed"
        )

        if success:
            self.log_success("Sketchybar reloaded")

    def _generate_dynamic_colors(self, theme_data: dict) -> str:
        """Generate bash script with dynamic theme colors"""
        mat = get_material_colors(theme_data)

        return f"""#!/bin/bash
# SketchyBar Colors - Dynamic theme
# Generated by theme system

# Helper function to convert #rrggbb to 0xffrrggbb (ARGB format)
hex_to_argb() {{
  local hex="${{1#\\#}}"  # Remove # if present
  echo "0xff${{hex}}"
}}

export FOREGROUND="$(hex_to_argb '{mat.get("on_surface", "#cdd6f4")}')"
export BACKGROUND="$(hex_to_argb '{mat.get("background", "#1e1e2e")}')"
export PRIMARY="$(hex_to_argb '{mat.get("primary", "#cba6f7")}')"
export SECONDARY="$(hex_to_argb '{mat.get("secondary", "#89b4fa")}')"
export TERTIARY="$(hex_to_argb '{mat.get("tertiary", "#a6e3a1")}')"
export ERROR="$(hex_to_argb '{mat.get("error", "#f38ba8")}')"
export SURFACE="$(hex_to_argb '{mat.get("surface", "#313244")}')"
export SURFACE_BRIGHT="$(hex_to_argb '{mat.get("surface_bright", "#585b70")}')"
export SURFACE_DIM="$(hex_to_argb '{mat.get("surface_dim", "#181825")}')"
export OUTLINE="$(hex_to_argb '{mat.get("outline", "#6c7086")}')"

# Semantic colors for Sketchybar (use these in your config)
export BAR_COLOR="$BACKGROUND"
export ICON_COLOR="$FOREGROUND"
export LABEL_COLOR="$FOREGROUND"
export ITEM_BG_COLOR="$SURFACE"
export ITEM_BG_BRIGHT="$SURFACE_BRIGHT"
export BORDER_COLOR="$OUTLINE"
export ACCENT_COLOR="$PRIMARY"
"""

    def _generate_static_colors(self, theme_data: dict) -> str:
        """Generate bash script with static Catppuccin colors"""
        ctp = get_catppuccin_colors(theme_data)
        theme_name = theme_data.get("theme", {}).get("name", "mocha")

        return f"""#!/bin/bash
# SketchyBar Colors - {theme_name.title()}
# Generated by theme system

# Helper function to convert #rrggbb to 0xffrrggbb (ARGB format)
hex_to_argb() {{
  local hex="${{1#\\#}}"  # Remove # if present
  echo "0xff${{hex}}"
}}

export FOREGROUND="$(hex_to_argb '{ctp.get("text", "#cdd6f4")}')"
export BACKGROUND="$(hex_to_argb '{ctp.get("base", "#1e1e2e")}')"
export PRIMARY="$(hex_to_argb '{ctp.get("mauve", "#cba6f7")}')"
export SECONDARY="$(hex_to_argb '{ctp.get("blue", "#89b4fa")}')"
export TERTIARY="$(hex_to_argb '{ctp.get("green", "#a6e3a1")}')"
export ERROR="$(hex_to_argb '{ctp.get("red", "#f38ba8")}')"
export SURFACE="$(hex_to_argb '{ctp.get("surface0", "#313244")}')"
export SURFACE_BRIGHT="$(hex_to_argb '{ctp.get("surface2", "#585b70")}')"
export SURFACE_DIM="$(hex_to_argb '{ctp.get("mantle", "#181825")}')"
export OUTLINE="$(hex_to_argb '{ctp.get("overlay0", "#6c7086")}')"

# Semantic colors for Sketchybar (use these in your config)
export BAR_COLOR="$BACKGROUND"
export ICON_COLOR="$FOREGROUND"
export LABEL_COLOR="$FOREGROUND"
export ITEM_BG_COLOR="$SURFACE"
export ITEM_BG_BRIGHT="$SURFACE_BRIGHT"
export BORDER_COLOR="$OUTLINE"
export ACCENT_COLOR="$PRIMARY"
"""
