"""Television fuzzy finder theme generator"""

from pathlib import Path
from .base import BaseApp
from utils import get_material_colors, is_dynamic_theme


class TelevisionTheme(BaseApp):
    """Television theme generator

    Method: hybrid (builtin for static, external_file for dynamic)
    Reload: on_demand (config read on each invocation)

    Television has excellent builtin theme support with catppuccin.
    Static themes: update config.toml to reference downloaded theme files
    Dynamic themes: generate themes/dynamic.toml with MD3 colors
    """

    def __init__(self, config_home: Path):
        super().__init__("Television", config_home)
        self.config_file = config_home / "television/config.toml"
        self.themes_dir = config_home / "television/themes"
        self.dynamic_theme = self.themes_dir / "dynamic.toml"

    def apply_theme(self, theme_data: dict) -> None:
        """Apply theme to Television

        For static themes: updates theme reference in config.toml
        For dynamic themes: generates dynamic.toml and updates reference
        """
        if not self.config_file.exists():
            self.log_warning(f"Television config not found: {self.config_file}")
            return

        self.log_progress("Updating Television theme")

        if is_dynamic_theme(theme_data):
            # Generate dynamic theme file
            self._generate_dynamic_theme(theme_data)
            theme_name = "dynamic"
        else:
            # Use downloaded Catppuccin theme
            variant = theme_data.get("theme", {}).get("name", "mocha")
            theme_name = f"catppuccin-{variant}-mauve"

            # Fallback to builtin catppuccin if custom theme file doesn't exist
            theme_file = self.themes_dir / f"{theme_name}.toml"
            if not theme_file.exists():
                self.log_warning(
                    f"Theme file not found: {theme_file}, using builtin catppuccin"
                )
                theme_name = "catppuccin"

        self._update_config(theme_name)

    def _generate_dynamic_theme(self, theme_data: dict) -> None:
        """Generate dynamic.toml from Material Design 3 colors

        Television has 17 color keys that map to various UI elements.
        """
        mat = get_material_colors(theme_data)

        content = f'''# Television Dynamic Theme
# Generated by theme system from wallpaper (Material Design 3)

# General
background = "{mat.get("surface", "#1e1e2e")}"
border_fg = "{mat.get("surface_container", "#45475a")}"
text_fg = "{mat.get("on_surface", "#cdd6f4")}"
dimmed_text_fg = "{mat.get("outline", "#6c7086")}"

# Input
input_text_fg = "{mat.get("primary", "#cba6f7")}"
result_count_fg = "{mat.get("primary", "#cba6f7")}"

# Results
result_name_fg = "{mat.get("secondary", "#89b4fa")}"
result_line_number_fg = "{mat.get("tertiary", "#f9e2af")}"
result_value_fg = "{mat.get("on_surface_variant", "#b4befe")}"
selection_fg = "{mat.get("tertiary", "#a6e3a1")}"
selection_bg = "{mat.get("surface_container_high", "#313244")}"
match_fg = "{mat.get("primary", "#a6e3a1")}"

# Preview
preview_title_fg = "{mat.get("primary", "#cba6f7")}"

# Modes
channel_mode_fg = "{mat.get("on_primary", "#1e1e2e")}"
channel_mode_bg = "{mat.get("primary", "#cba6f7")}"
remote_control_mode_fg = "{mat.get("on_tertiary", "#1e1e2e")}"
remote_control_mode_bg = "{mat.get("tertiary", "#a6e3a1")}"
'''

        # Ensure themes directory exists
        self.themes_dir.mkdir(parents=True, exist_ok=True)
        self.write_file(self.dynamic_theme, content)

    def _update_config(self, theme_name: str) -> None:
        """Update config.toml with theme reference using tomlkit

        Surgically updates only the theme key, preserving all other config.
        """
        try:
            import tomlkit
        except ImportError:
            self.log_error("tomlkit not available - cannot update Television config")
            self.log_warning("Install with: pip install tomlkit")
            return

        try:
            with open(self.config_file, "r") as f:
                config = tomlkit.load(f)

            # Ensure [ui] section exists
            if "ui" not in config:
                config["ui"] = tomlkit.table()

            # Update theme reference
            config["ui"]["theme"] = theme_name

            with open(self.config_file, "w") as f:
                tomlkit.dump(config, f)

            self.log_success(f'Updated Television: theme = "{theme_name}"')

        except Exception as e:
            self.log_error(f"Failed to update Television config: {e}")
