"""WezTerm theme generator"""

from pathlib import Path
from .base import BaseApp
from utils import get_material_colors, get_catppuccin_colors, is_dynamic_theme, get_theme_variant, opacity_to_alpha


class WeztermTheme(BaseApp):
    """WezTerm terminal emulator theme generator
    
    Generates:
    - colors-wezterm.lua: Color palette with mode-aware ANSI colors
    - opacity-wezterm.lua: Opacity and blur settings
    
    WezTerm auto-reloads configuration files, so no explicit reload needed.
    """
    
    def __init__(self, config_home: Path):
        super().__init__("WezTerm", config_home)
        self.colors_file = config_home / "wezterm/colors-wezterm.lua"
        self.opacity_file = config_home / "wezterm/opacity-wezterm.lua"
    
    def apply_theme(self, theme_data: dict) -> None:
        """Apply theme to WezTerm"""
        self.generate_colors(theme_data)
        self.generate_opacity(theme_data)
        # Note: WezTerm auto-reloads, no explicit reload needed
    
    def generate_colors(self, theme_data: dict) -> None:
        """Generate colors-wezterm.lua with mode-aware ANSI colors"""
        self.log_progress("Generating WezTerm colors")
        
        if is_dynamic_theme(theme_data):
            content = self._generate_dynamic_colors(theme_data)
        else:
            content = self._generate_static_colors(theme_data)
        
        self.write_file(self.colors_file, content)
    
    def generate_opacity(self, theme_data: dict) -> None:
        """Generate opacity-wezterm.lua"""
        theme = theme_data.get("theme", {})
        opacity_percent = theme.get("opacity", 0)
        
        if opacity_percent > 0:
            opacity_value = opacity_to_alpha(opacity_percent, format="float")
            content = f"""-- WezTerm Opacity - Generated by theme system
-- Opacity: {opacity_percent}% (0=invisible, 100=solid)

return {{
  enabled = true,
  opacity = {opacity_value},
  blur = 80,
}}
"""
        else:
            content = """-- WezTerm Opacity - Generated by theme system
-- Opacity: 0% (fully opaque)

return {
  enabled = false,
}
"""
        
        self.write_file(self.opacity_file, content)
    
    def _generate_dynamic_colors(self, theme_data: dict) -> str:
        """Generate Lua colors for dynamic theme"""
        mat = get_material_colors(theme_data)
        variant = get_theme_variant(theme_data)
        
        # Mode-aware ANSI color mapping
        if variant == "light":
            ansi_colors = self._get_light_ansi_colors(mat)
        else:
            ansi_colors = self._get_dark_ansi_colors(mat)
        
        return f"""-- WezTerm Colors - Generated by theme system
-- Dynamic theme: Material Design 3 from wallpaper ({variant} mode)

local colors = {{}}

-- Basic
colors.foreground = "{mat.get("on_surface", "#cdd6f4")}"
colors.background = "{mat.get("background", "#1e1e2e")}"

-- Cursor
colors.cursor_bg = "{mat.get("primary", "#cba6f7")}"
colors.cursor_fg = "{mat.get("on_primary", "#11111b")}"
colors.cursor_border = "{mat.get("primary", "#cba6f7")}"

-- Selection
colors.selection_bg = "{mat.get("primary_container", "#45475a")}"
colors.selection_fg = "{mat.get("on_primary_container", "#cdd6f4")}"

-- ANSI colors (Mode-aware mapping)
{ansi_colors}

return colors
"""
    
    def _generate_static_colors(self, theme_data: dict) -> str:
        """Generate Lua colors for static Catppuccin theme"""
        ctp = get_catppuccin_colors(theme_data)
        theme_name = theme_data.get("theme", {}).get("name", "mocha")
        
        return f"""-- WezTerm Colors - Generated by theme system
-- Static theme: Catppuccin {theme_name.title()} with Mauve accents

local colors = {{}}

-- Basic
colors.foreground = "{ctp.get("text", "#cdd6f4")}"
colors.background = "{ctp.get("base", "#1e1e2e")}"

-- Cursor
colors.cursor_bg = "{ctp.get("mauve", "#cba6f7")}"
colors.cursor_fg = "{ctp.get("crust", "#11111b")}"
colors.cursor_border = "{ctp.get("mauve", "#cba6f7")}"

-- Selection
colors.selection_bg = "{ctp.get("surface2", "#585b70")}"
colors.selection_fg = "{ctp.get("text", "#cdd6f4")}"

-- Split border
colors.split = "{ctp.get("mauve", "#cba6f7")}"

-- Catppuccin ANSI colors
colors.ansi = {{
  "{ctp.get("surface1", "#45475a")}",  -- black
  "{ctp.get("red", "#f38ba8")}",       -- red
  "{ctp.get("green", "#a6e3a1")}",     -- green
  "{ctp.get("yellow", "#f9e2af")}",    -- yellow
  "{ctp.get("blue", "#89b4fa")}",      -- blue
  "{ctp.get("mauve", "#cba6f7")}",     -- magenta (Mauve!)
  "{ctp.get("teal", "#94e2d5")}",      -- cyan
  "{ctp.get("subtext1", "#bac2de")}",  -- white
}}

colors.brights = {{
  "{ctp.get("surface2", "#585b70")}",  -- bright black
  "{ctp.get("red", "#f38ba8")}",       -- bright red
  "{ctp.get("green", "#a6e3a1")}",     -- bright green
  "{ctp.get("yellow", "#f9e2af")}",    -- bright yellow
  "{ctp.get("blue", "#89b4fa")}",      -- bright blue
  "{ctp.get("mauve", "#cba6f7")}",     -- bright magenta (Mauve!)
  "{ctp.get("teal", "#94e2d5")}",      -- bright cyan
  "{ctp.get("subtext0", "#a6adc8")}",  -- bright white
}}

return colors
"""
    
    def _get_light_ansi_colors(self, mat: dict) -> str:
        """Get ANSI colors for light mode"""
        return f"""colors.ansi = {{
  "{mat.get("outline", "#73796f")}",                 -- black (dark gray)
  "{mat.get("error", "#ba1a1a")}",                   -- red (dark red)
  "{mat.get("primary", "#775930")}",                -- green (dark olive/brown)
  "{mat.get("secondary", "#765658")}",               -- yellow (dark mauve/brown)
  "{mat.get("tertiary", "#8f4a50")}",                 -- blue (dark rose/blue)
  "{mat.get("primary", "#775930")}",                -- magenta (dark olive)
  "{mat.get("tertiary", "#8f4a50")}",                 -- cyan (dark rose/blue)
  "{mat.get("on_surface", "#22191a")}",              -- white (very dark text)
}}

colors.brights = {{
  "{mat.get("outline", "#857373")}",                 -- bright black (medium gray)
  "{mat.get("error", "#ba1a1a")}",                   -- bright red (dark red)
  "{mat.get("primary", "#775930")}",                -- bright green (dark olive)
  "{mat.get("secondary", "#765658")}",               -- bright yellow (dark mauve)
  "{mat.get("tertiary", "#8f4a50")}",                 -- bright blue (dark rose)
  "{mat.get("primary", "#775930")}",                -- bright magenta (dark olive)
  "{mat.get("tertiary", "#8f4a50")}",                 -- bright cyan (dark rose)
  "{mat.get("on_surface", "#22191a")}",              -- bright white (very dark text)
}}"""
    
    def _get_dark_ansi_colors(self, mat: dict) -> str:
        """Get ANSI colors for dark mode"""
        return f"""colors.ansi = {{
  "{mat.get("outline", "#8d9199")}",           -- black (medium gray)
  "{mat.get("error", "#f38ba8")}",             -- red (salmon pink)
  "{mat.get("primary", "#a6e3a1")}",          -- green (light purple)
  "{mat.get("secondary", "#89b4fa")}",         -- yellow (blue-gray)
  "{mat.get("tertiary", "#cba6f7")}",           -- blue (light blue)
  "{mat.get("primary_fixed", "#f7d8ff")}",    -- magenta (very light purple)
  "{mat.get("tertiary_fixed", "#d4e3ff")}",     -- cyan (very light blue)
  "{mat.get("on_surface", "#cdd6f4")}",        -- white (light gray)
}}

colors.brights = {{
  "{mat.get("outline", "#8d9199")}",           -- bright black (medium gray)
  "{mat.get("error", "#f38ba8")}",             -- bright red (salmon pink)
  "{mat.get("primary_fixed", "#f7d8ff")}",    -- bright green (very light purple)
  "{mat.get("secondary_fixed", "#d8e3f8")}",   -- bright yellow (very light blue-gray)
  "{mat.get("tertiary_fixed", "#d4e3ff")}",     -- bright blue (very light blue)
  "{mat.get("primary_fixed", "#f7d8ff")}",    -- bright magenta (very light purple)
  "{mat.get("tertiary_fixed", "#d4e3ff")}",     -- bright cyan (very light blue)
  "{mat.get("on_surface_variant", "#bac2de")}",-- bright white (medium light gray)
}}"""
