"""Yazi terminal file manager theme generator"""

from pathlib import Path
from .base import BaseApp
from utils import get_material_colors, get_catppuccin_colors, is_dynamic_theme


class YaziTheme(BaseApp):
    """Yazi theme generator

    Method: external_file (generates flavor.toml in flavors directory)
    Reload: manual (requires restart - yazi does NOT support hot reload)

    Yazi uses a "flavor" system for theming:
    - Flavors are directories: ~/.config/yazi/flavors/{name}.yazi/
    - Each flavor contains a flavor.toml file
    - theme.toml references flavors via [flavor] dark/light keys

    Static themes: Pre-created Catppuccin flavors (managed by chezmoi)
    Dynamic themes: Generate dynamic.yazi/flavor.toml with MD3 colors
    """

    def __init__(self, config_home: Path):
        super().__init__("Yazi", config_home)
        self.theme_file = config_home / "yazi/theme.toml"
        self.flavors_dir = config_home / "yazi/flavors"
        self.dynamic_flavor_dir = self.flavors_dir / "dynamic.yazi"
        self.dynamic_flavor_file = self.dynamic_flavor_dir / "flavor.toml"

    def apply_theme(self, theme_data: dict) -> None:
        """Apply theme to Yazi

        For static themes: updates theme.toml to reference Catppuccin flavor
        For dynamic themes: generates dynamic.yazi/flavor.toml and updates reference
        """
        self.log_progress("Updating Yazi theme")

        if is_dynamic_theme(theme_data):
            # Generate dynamic flavor file
            self._generate_dynamic_flavor(theme_data)
            flavor_name = "dynamic"
        else:
            # Use pre-created Catppuccin flavor
            variant = theme_data.get("theme", {}).get("name", "mocha")
            flavor_name = f"catppuccin-{variant}"

        # Update theme.toml to reference the flavor
        self._update_theme_reference(flavor_name, theme_data)

        self.log_warning("Restart yazi to apply theme (no hot reload support)")

    def _generate_dynamic_flavor(self, theme_data: dict) -> None:
        """Generate dynamic.yazi/flavor.toml from Material Design 3 colors"""
        mat = get_material_colors(theme_data)
        variant = theme_data.get("theme", {}).get("variant", "dark")

        # Determine base/contrast colors based on light/dark mode
        if variant == "light":
            bg_base = mat.get("background", "#eff1f5")
            fg_text = mat.get("on_surface", "#4c4f69")
            surface0 = mat.get("surface_container", "#ccd0da")
            surface1 = mat.get("surface_container_high", "#bcc0cc")
            surface2 = mat.get("surface_container_highest", "#acb0be")
            overlay0 = mat.get("outline", "#9ca0b0")
            mode_fg = bg_base
        else:
            bg_base = mat.get("background", "#1e1e2e")
            fg_text = mat.get("on_surface", "#cdd6f4")
            surface0 = mat.get("surface_container", "#313244")
            surface1 = mat.get("surface_container_high", "#45475a")
            surface2 = mat.get("surface_container_highest", "#585b70")
            overlay0 = mat.get("outline", "#6c7086")
            mode_fg = bg_base

        # Get accent colors
        primary = mat.get("primary", "#cba6f7")
        secondary = mat.get("secondary", "#89b4fa")
        tertiary = mat.get("tertiary", "#a6e3a1")
        error = mat.get("error", "#f38ba8")
        warning = mat.get("secondary", "#f9e2af")

        content = f'''# Yazi Dynamic Flavor
# Generated by theme system from wallpaper (Material Design 3)
# Variant: {variant}

# ============================================================================
# Manager (main file list)
# ============================================================================
[mgr]
cwd = {{ fg = "{tertiary}" }}
hovered = {{ reversed = true }}
preview_hovered = {{ underline = true }}
find_keyword = {{ fg = "{warning}", bold = true, italic = true, underline = true }}
find_position = {{ fg = "{mat.get("tertiary_fixed", tertiary)}", bg = "reset", bold = true, italic = true }}
marker_copied = {{ fg = "{tertiary}", bg = "{tertiary}" }}
marker_cut = {{ fg = "{error}", bg = "{error}" }}
marker_marked = {{ fg = "{secondary}", bg = "{secondary}" }}
marker_selected = {{ fg = "{warning}", bg = "{warning}" }}
border_style = {{ fg = "{overlay0}" }}
border_symbol = "│"
count_copied = {{ fg = "{mode_fg}", bg = "{tertiary}" }}
count_cut = {{ fg = "{mode_fg}", bg = "{error}" }}
count_selected = {{ fg = "{mode_fg}", bg = "{warning}" }}

syntect_theme = ""

# ============================================================================
# Tabs
# ============================================================================
[tabs]
active = {{ fg = "{mode_fg}", bg = "{primary}", bold = true }}
inactive = {{ fg = "{primary}", bg = "{surface0}" }}

# ============================================================================
# Mode indicators (bottom left)
# ============================================================================
[mode]
normal_main = {{ fg = "{mode_fg}", bg = "{primary}", bold = true }}
normal_alt = {{ fg = "{primary}", bg = "{surface0}" }}
select_main = {{ fg = "{mode_fg}", bg = "{tertiary}", bold = true }}
select_alt = {{ fg = "{tertiary}", bg = "{surface0}" }}
unset_main = {{ fg = "{mode_fg}", bg = "{mat.get("tertiary_fixed", tertiary)}", bold = true }}
unset_alt = {{ fg = "{mat.get("tertiary_fixed", tertiary)}", bg = "{surface0}" }}

# ============================================================================
# Status bar (bottom)
# ============================================================================
[status]
sep_left = {{ open = "", close = "", fg = "{surface2}", bg = "{surface2}" }}
sep_right = {{ open = "", close = "", fg = "{surface2}", bg = "{surface2}" }}
sep_style = {{ fg = "{mode_fg}", bg = "{surface2}" }}

progress_label = {{ fg = "{fg_text}", bold = true }}
progress_normal = {{ fg = "{primary}", bg = "{surface0}" }}
progress_error = {{ fg = "{error}", bg = "{surface0}" }}

perm_sep = {{ fg = "{overlay0}" }}
perm_type = {{ fg = "{primary}" }}
perm_read = {{ fg = "{warning}" }}
perm_write = {{ fg = "{error}" }}
perm_exec = {{ fg = "{tertiary}" }}

# ============================================================================
# Confirmation dialogs
# ============================================================================
[confirm]
border = {{ fg = "{primary}" }}
title = {{ fg = "{primary}" }}
content = {{ fg = "{fg_text}" }}
list = {{ fg = "{fg_text}" }}
btn_yes = {{ bg = "{tertiary}" }}
btn_no = {{ bg = "{error}" }}
btn_label = {{ bold = true }}

# ============================================================================
# Input fields
# ============================================================================
[input]
border = {{ fg = "{primary}" }}
title = {{ fg = "{primary}" }}
value = {{ fg = "{fg_text}" }}
value_bg = {{ bg = "{surface0}" }}
selected = {{ reversed = true }}

# ============================================================================
# Completion menu
# ============================================================================
[cmp]
border = {{ fg = "{primary}" }}
active = {{ fg = "{mode_fg}", bg = "{primary}" }}
inactive = {{ fg = "{fg_text}" }}

# ============================================================================
# Help popup
# ============================================================================
[help]
on = {{ fg = "{secondary}" }}
run = {{ fg = "{primary}" }}
desc = {{ fg = "{fg_text}" }}
hovered = {{ reversed = true, bold = true }}
footer = {{ fg = "{overlay0}" }}

# ============================================================================
# Which-key popup
# ============================================================================
[which]
sep = {{ fg = "{surface2}" }}
cols = 3
mask = {{ bg = "{surface0}" }}
rest = {{ fg = "{overlay0}" }}
cand = {{ fg = "{secondary}" }}
desc = {{ fg = "{fg_text}" }}

# ============================================================================
# Notifications
# ============================================================================
[notify]
title_info = {{ fg = "{tertiary}" }}
title_warn = {{ fg = "{warning}" }}
title_error = {{ fg = "{error}" }}

# ============================================================================
# Picker menus
# ============================================================================
[pick]
border = {{ fg = "{primary}" }}
active = {{ fg = "{mode_fg}", bg = "{primary}" }}
inactive = {{ fg = "{fg_text}" }}

# ============================================================================
# Task manager
# ============================================================================
[tasks]
border = {{ fg = "{primary}" }}
title = {{ fg = "{primary}" }}
hovered = {{ fg = "{primary}", underline = true }}

# ============================================================================
# Spot preview
# ============================================================================
[spot]
border = {{ fg = "{primary}" }}
title = {{ fg = "{primary}" }}

# ============================================================================
# File type colors
# ============================================================================
[filetype]
rules = [
    # Directories
    {{ url = "*/", fg = "{secondary}" }},

    # Executables
    {{ is = "exec", fg = "{tertiary}" }},

    # Media files
    {{ mime = "image/*", fg = "{mat.get("tertiary_fixed", tertiary)}" }},
    {{ mime = "{{audio,video}}/*", fg = "{warning}" }},

    # Documents
    {{ mime = "application/pdf", fg = "{error}" }},
    {{ mime = "application/*zip*", fg = "{mat.get("secondary_fixed", secondary)}" }},
    {{ mime = "application/x-tar", fg = "{mat.get("secondary_fixed", secondary)}" }},
    {{ mime = "application/x-bzip*", fg = "{mat.get("secondary_fixed", secondary)}" }},
    {{ mime = "application/x-7z*", fg = "{mat.get("secondary_fixed", secondary)}" }},
    {{ mime = "application/x-rar", fg = "{mat.get("secondary_fixed", secondary)}" }},
    {{ mime = "application/x-xz", fg = "{mat.get("secondary_fixed", secondary)}" }},

    # Plain text / config files
    {{ mime = "text/*", fg = "{fg_text}" }},

    # Symlinks
    {{ is = "link", fg = "{secondary}" }},
    {{ is = "orphan", fg = "{error}" }},
]

# ============================================================================
# Icons (optional)
# ============================================================================
[icon]
prepend_dirs = []
prepend_files = []
prepend_exts = []
'''

        # Ensure flavor directory exists
        self.dynamic_flavor_dir.mkdir(parents=True, exist_ok=True)
        self.write_file(self.dynamic_flavor_file, content)

    def _update_theme_reference(self, flavor_name: str, theme_data: dict) -> None:
        """Update theme.toml with flavor reference using tomlkit

        Updates [flavor] dark/light keys based on theme variant.
        """
        try:
            import tomlkit
        except ImportError:
            self.log_error("tomlkit not available - cannot update Yazi theme.toml")
            self.log_warning("Install with: pip install tomlkit")
            return

        if not self.theme_file.exists():
            self.log_warning(f"Yazi theme.toml not found: {self.theme_file}")
            return

        try:
            with open(self.theme_file, "r") as f:
                config = tomlkit.load(f)

            # Ensure [flavor] section exists
            if "flavor" not in config:
                config["flavor"] = tomlkit.table()

            # For dynamic themes: set BOTH dark and light to ensure consistency
            # (headless systems can't detect system dark/light mode, so yazi defaults to dark)
            # For static themes: only update the matching variant key
            if is_dynamic_theme(theme_data):
                config["flavor"]["dark"] = flavor_name
                config["flavor"]["light"] = flavor_name
                log_msg = f'Updated Yazi: flavor.dark = flavor.light = "{flavor_name}"'
            else:
                variant = theme_data.get("theme", {}).get("variant", "dark")
                if variant == "light":
                    config["flavor"]["light"] = flavor_name
                else:
                    config["flavor"]["dark"] = flavor_name
                log_msg = f'Updated Yazi: flavor.{variant} = "{flavor_name}"'

            with open(self.theme_file, "w") as f:
                tomlkit.dump(config, f)

            self.log_success(log_msg)

        except Exception as e:
            self.log_error(f"Failed to update Yazi theme.toml: {e}")
