"""Zellij theme generator"""

from pathlib import Path
from .base import BaseApp
from utils import get_material_colors, get_catppuccin_colors, is_dynamic_theme


class ZellijTheme(BaseApp):
    """Zellij terminal multiplexer theme generator

    Generates:
    - dynamic.kdl: Theme file with Material Design 3 colors

    Zellij has built-in file watching for theme files, so changes
    take effect immediately without restart or reload command.

    Architecture:
    - Static themes: Use pre-existing catppuccin-{variant}.kdl files
    - Dynamic themes: Generate dynamic.kdl with wallpaper-derived colors
    - config.kdl (managed by chezmoi) references theme by name
    """

    def __init__(self, config_home: Path):
        super().__init__("Zellij", config_home)
        self.themes_dir = config_home / "zellij/themes"
        self.dynamic_theme_file = self.themes_dir / "dynamic.kdl"

    def apply_theme(self, theme_data: dict) -> None:
        """Apply theme to Zellij

        For dynamic themes: Generate dynamic.kdl with Material colors
        For static themes: Just log (chezmoi handles config.kdl)

        Zellij auto-reloads theme files via file watching.
        """
        if is_dynamic_theme(theme_data):
            self.generate_dynamic_theme(theme_data)
        else:
            # Static themes are handled by chezmoi template
            # config.kdl references catppuccin-{variant} theme
            theme_name = theme_data.get("theme", {}).get("name", "mocha")
            self.log_success(f"Using static theme: catppuccin-{theme_name}")

    def generate_dynamic_theme(self, theme_data: dict) -> None:
        """Generate dynamic.kdl theme file with Material colors

        Maps Material Design 3 colors to Zellij's terminal color slots.
        Zellij will auto-reload this file when it changes.
        """
        self.log_progress("Generating Zellij dynamic theme", emoji="🖥️")

        mat = get_material_colors(theme_data)

        # Map Material colors to terminal ANSI colors
        # Using semantic mappings that make sense for terminal use
        colors = {
            "bg": mat.get("background", "#1e1e2e"),
            "fg": mat.get("on_surface", "#cdd6f4"),
            "black": mat.get("scrim", "#11111b"),
            "red": mat.get("error", "#f38ba8"),
            "green": mat.get("tertiary", "#a6e3a1"),
            "yellow": mat.get("secondary", "#f9e2af"),
            "blue": mat.get("primary", "#89b4fa"),
            "magenta": mat.get("primary", "#cba6f7"),  # Primary as accent
            "cyan": mat.get("tertiary", "#94e2d5"),
            "white": mat.get("on_surface", "#cdd6f4"),
            "orange": mat.get("secondary", "#fab387"),
        }

        kdl_content = f"""// Dynamic theme for Zellij - Generated from wallpaper colors
// Auto-generated by theme system - DO NOT EDIT
// Zellij auto-reloads this file when it changes

themes {{
    dynamic {{
        bg "{colors["bg"]}"
        fg "{colors["fg"]}"
        red "{colors["red"]}"
        green "{colors["green"]}"
        yellow "{colors["yellow"]}"
        blue "{colors["blue"]}"
        magenta "{colors["magenta"]}"
        cyan "{colors["cyan"]}"
        orange "{colors["orange"]}"
        black "{colors["black"]}"
        white "{colors["white"]}"
    }}
}}
"""

        self.write_file(self.dynamic_theme_file, kdl_content)
        self.log_success("Zellij will auto-reload theme (file watching)")
