"""Zellij theme generator"""

import subprocess
from pathlib import Path
from .base import BaseApp
from utils import get_material_colors, is_dynamic_theme


class ZellijTheme(BaseApp):
    """Zellij terminal multiplexer theme generator

    Generates themes/dynamic.kdl and triggers chezmoi apply for hot-reload.

    Zellij watches config.kdl for changes. Triggering chezmoi apply on
    config.kdl reliably triggers the hot-reload mechanism.

    Architecture:
    - Dynamic themes: Write themes/dynamic.kdl + chezmoi apply for reload
    - Static themes: Use built-in Catppuccin (no generation needed)
    """

    def __init__(self, config_home: Path):
        super().__init__("Zellij", config_home)
        self.config_file = config_home / "zellij/config.kdl"
        self.themes_dir = config_home / "zellij/themes"
        self.dynamic_theme_file = self.themes_dir / "dynamic.kdl"

    def apply_theme(self, theme_data: dict) -> None:
        """Apply theme to Zellij

        For dynamic themes: Write theme file and trigger reload via chezmoi
        For static themes: Just log (built-in themes work automatically)
        """
        if is_dynamic_theme(theme_data):
            self.generate_dynamic_theme(theme_data)
            self.trigger_reload()
        else:
            # Static themes use Zellij's built-in Catppuccin
            theme_name = theme_data.get("theme", {}).get("name", "mocha")
            self.log_success(f"Using built-in theme: catppuccin-{theme_name}")

    def generate_dynamic_theme(self, theme_data: dict) -> None:
        """Generate dynamic.kdl theme file with Material colors"""
        self.log_progress("Generating Zellij dynamic theme", emoji="🖥️")

        mat = get_material_colors(theme_data)

        # Map Material colors to terminal ANSI colors
        colors = {
            "bg": mat.get("background", "#1e1e2e"),
            "fg": mat.get("on_surface", "#cdd6f4"),
            "black": mat.get("scrim", "#11111b"),
            "red": mat.get("error", "#f38ba8"),
            "green": mat.get("tertiary", "#a6e3a1"),
            "yellow": mat.get("secondary", "#f9e2af"),
            "blue": mat.get("primary", "#89b4fa"),
            "magenta": mat.get("primary", "#cba6f7"),
            "cyan": mat.get("tertiary", "#94e2d5"),
            "white": mat.get("on_surface", "#cdd6f4"),
            "orange": mat.get("secondary", "#fab387"),
        }

        kdl_content = f"""// Dynamic theme for Zellij - Generated from wallpaper colors
// Auto-generated by theme system
themes {{
    dynamic {{
        bg "{colors["bg"]}"
        fg "{colors["fg"]}"
        red "{colors["red"]}"
        green "{colors["green"]}"
        yellow "{colors["yellow"]}"
        blue "{colors["blue"]}"
        magenta "{colors["magenta"]}"
        cyan "{colors["cyan"]}"
        orange "{colors["orange"]}"
        black "{colors["black"]}"
        white "{colors["white"]}"
    }}
}}
"""

        self.write_file(self.dynamic_theme_file, kdl_content)

    def trigger_reload(self) -> None:
        """Trigger Zellij hot-reload by re-applying config.kdl via chezmoi.

        Zellij reliably hot-reloads when chezmoi applies the config file.
        This is a workaround since direct file writes don't trigger reload.
        """
        if not self.command_exists("chezmoi"):
            self.log_warning("chezmoi not found, Zellij won't hot-reload")
            return

        try:
            subprocess.run(
                ["chezmoi", "apply", "--force", str(self.config_file)],
                capture_output=True,
                timeout=10,
                check=True,
            )
            self.log_success("Zellij hot-reload triggered via chezmoi")
        except subprocess.CalledProcessError as e:
            self.log_warning(f"chezmoi apply failed: {e}")
        except subprocess.TimeoutExpired:
            self.log_warning("chezmoi apply timed out")
