// Dedicated Quickshell wallpaper instance.
// Run:    qs -p ~/.config/quickshell/wallpaper
// Toggle: qs -p ~/.config/quickshell/wallpaper ipc call wallpaper toggle
// Colors are generated by the theme-system QuickshellWallpaperTheme plugin and
// reloaded via the `theme-manager` IPC target below.
import Quickshell
import Quickshell.Io
import qs.CustomTheme

ShellRoot {
    id: root

    IpcHandler {
        target: "theme-manager"
        function reload(): void {
            Theme.reloadTheme()
            wallpaperWindow.refreshFolder()
        }
    }

    WallpaperWindow {
        id: wallpaperWindow
    }
}
