pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io

// Color contract for the voice-typer HUD instance.
// Colors are generated by the theme-system QuickshellVoiceTheme plugin into
// ~/.config/quickshell/voice/colors.json and reloaded via the `voice`
// IPC target (reloadTheme) in shell.qml.
QtObject {
    id: root

    readonly property string fontFamily: "JetBrainsMono Nerd Font"

    // Material Design 3 tokens (overwritten from colors.json when available).
    property color background: "#1e1e2e"
    property color error: "#f38ba8"
    property color on_error: "#11111b"
    property color on_surface: "#cdd6f4"
    property color on_surface_variant: "#bac2de"
    property color outline: "#6c7086"
    property color outline_variant: "#585b70"
    property color primary: "#cba6f7"
    property color on_primary: "#11111b"
    property color primary_container: "#313244"
    property color secondary: "#89b4fa"
    property color surface: "#1e1e2e"
    property color surface_container: "#1e1e2e"
    property color surface_container_high: "#313244"
    property color surface_container_highest: "#45475a"
    property color tertiary: "#a6e3a1"

    property var themeReader: Process {
        id: reader
        command: ["bash", "-c", "cat \"$HOME/.config/quickshell/voice/colors.json\" 2>/dev/null"]
        stdout: StdioCollector {
            onStreamFinished: {
                const output = this.text.trim();
                if (output === "")
                    return;
                try {
                    const newColors = JSON.parse(output);
                    for (const key in newColors) {
                        if (root.hasOwnProperty(key) && key !== "objectName") {
                            root[key] = newColors[key];
                        }
                    }
                } catch (e) {
                    console.log("Voice theme JSON parse failed: " + e);
                }
            }
        }
    }

    function reloadTheme() {
        reader.running = false;
        reader.running = true;
    }

    Component.onCompleted: reloadTheme()
}
