-- Dynamic Theme - Standalone Colorscheme
-- Generated from Material Design 3 wallpaper colors
-- This is a complete colorscheme, not an override of Catppuccin

vim.cmd("hi clear")
if vim.fn.exists("syntax_on") then
  vim.cmd("syntax reset")
end

vim.g.colors_name = "dynamic"

-- Load color palette from external file
local ok, colors = pcall(require, 'themes.colors-nvim')
if not ok or next(colors) == nil then
  vim.notify("Dynamic theme colors not found, falling back to catppuccin-mocha", vim.log.levels.WARN)
  vim.schedule(function()
    vim.cmd("colorscheme catppuccin-mocha")
  end)
  return
end

-- Load opacity configuration
local opacity_ok, opacity_config = pcall(require, 'config.opacity')
local transparent_bg = opacity_ok and opacity_config.transparent_background or false

-- Helper function to set highlight
local function hl(group, opts)
  opts.force = true
  vim.api.nvim_set_hl(0, group, opts)
end

-- Base highlight groups
hl("Normal", { fg = colors.text, bg = transparent_bg and "NONE" or colors.base })
hl("NormalFloat", { fg = colors.text, bg = transparent_bg and "NONE" or colors.mantle })
hl("NormalNC", { fg = colors.text, bg = transparent_bg and "NONE" or colors.base })

-- UI Elements
hl("ColorColumn", { bg = colors.surface0 })
hl("Cursor", { fg = colors.base, bg = colors.mauve })
hl("lCursor", { fg = colors.base, bg = colors.mauve })
hl("CursorIM", { fg = colors.base, bg = colors.mauve })
hl("CursorColumn", { bg = colors.surface0 })
hl("CursorLine", { bg = colors.surface0 })
hl("Directory", { fg = colors.blue })
hl("DiffAdd", { bg = colors.green, fg = colors.base })
hl("DiffChange", { bg = colors.yellow, fg = colors.base })
hl("DiffDelete", { bg = colors.red, fg = colors.base })
hl("DiffText", { bg = colors.blue, fg = colors.base })
hl("EndOfBuffer", { fg = colors.base })
hl("TermCursor", { fg = colors.base, bg = colors.mauve })
hl("TermCursorNC", { fg = colors.base, bg = colors.overlay0 })
hl("ErrorMsg", { fg = colors.red, bold = true })
hl("WinSeparator", { fg = colors.overlay0 })
hl("Folded", { fg = colors.overlay1, bg = colors.surface0 })
hl("FoldColumn", { fg = colors.overlay0, bg = colors.base })
hl("SignColumn", { fg = colors.overlay0, bg = transparent_bg and "NONE" or colors.base })
hl("IncSearch", { fg = colors.base, bg = colors.yellow })
hl("Substitute", { fg = colors.base, bg = colors.green })
hl("LineNr", { fg = colors.overlay0 })
hl("CursorLineNr", { fg = colors.mauve, bold = true })
hl("MatchParen", { fg = colors.peach, bold = true })
hl("ModeMsg", { fg = colors.text, bold = true })
hl("MsgArea", { fg = colors.text })
hl("MsgSeparator", { fg = colors.overlay0 })
hl("MoreMsg", { fg = colors.green })
hl("NonText", { fg = colors.overlay0 })
hl("Pmenu", { fg = colors.text, bg = colors.surface0 })
hl("PmenuSel", { fg = colors.base, bg = colors.mauve, bold = true })
hl("PmenuSbar", { bg = colors.surface1 })
hl("PmenuThumb", { bg = colors.overlay0 })
hl("Question", { fg = colors.blue })
hl("QuickFixLine", { bg = colors.surface1, bold = true })
hl("Search", { fg = colors.base, bg = colors.sky })
hl("SpecialKey", { fg = colors.overlay0 })
hl("SpellBad", { sp = colors.red, undercurl = true })
hl("SpellCap", { sp = colors.yellow, undercurl = true })
hl("SpellLocal", { sp = colors.blue, undercurl = true })
hl("SpellRare", { sp = colors.green, undercurl = true })
hl("StatusLine", { fg = colors.text, bg = colors.mantle })
hl("StatusLineNC", { fg = colors.overlay1, bg = colors.mantle })
hl("TabLine", { fg = colors.overlay1, bg = colors.surface0 })
hl("TabLineFill", { bg = colors.base })
hl("TabLineSel", { fg = colors.base, bg = colors.mauve })
hl("Title", { fg = colors.blue, bold = true })
hl("Visual", { bg = colors.surface1, bold = true })
hl("VisualNOS", { bg = colors.surface1 })
hl("WarningMsg", { fg = colors.yellow })
hl("Whitespace", { fg = colors.surface1 })
hl("WildMenu", { fg = colors.base, bg = colors.mauve })

-- Syntax highlighting
hl("Comment", { fg = colors.overlay1, italic = true })
hl("Constant", { fg = colors.peach })
hl("String", { fg = colors.yellow })
hl("Character", { fg = colors.yellow })
hl("Number", { fg = colors.peach })
hl("Boolean", { fg = colors.peach })
hl("Float", { fg = colors.peach })
hl("Identifier", { fg = colors.text })
hl("Function", { fg = colors.green })
hl("Statement", { fg = colors.mauve })
hl("Conditional", { fg = colors.mauve, italic = true })
hl("Repeat", { fg = colors.mauve, italic = true })
hl("Label", { fg = colors.mauve })
hl("Operator", { fg = colors.sky })
hl("Keyword", { fg = colors.mauve })
hl("Exception", { fg = colors.red })
hl("PreProc", { fg = colors.pink })
hl("Include", { fg = colors.pink })
hl("Define", { fg = colors.pink })
hl("Macro", { fg = colors.pink })
hl("PreCondit", { fg = colors.pink })
hl("Type", { fg = colors.blue })
hl("StorageClass", { fg = colors.blue })
hl("Structure", { fg = colors.blue })
hl("Typedef", { fg = colors.blue })
hl("Special", { fg = colors.pink })
hl("SpecialChar", { fg = colors.pink })
hl("Tag", { fg = colors.mauve })
hl("Delimiter", { fg = colors.overlay2 })
hl("SpecialComment", { fg = colors.overlay1, italic = true })
hl("Debug", { fg = colors.red })
hl("Underlined", { underline = true })
hl("Ignore", { fg = colors.overlay0 })
hl("Error", { fg = colors.red, bold = true })
hl("Todo", { fg = colors.base, bg = colors.yellow, bold = true })

-- Treesitter
hl("@variable", { fg = colors.text })
hl("@variable.builtin", { fg = colors.red })
hl("@variable.parameter", { fg = colors.peach })
hl("@variable.member", { fg = colors.text })
hl("@constant", { fg = colors.peach })
hl("@constant.builtin", { fg = colors.peach })
hl("@constant.macro", { fg = colors.pink })
hl("@module", { fg = colors.blue })
hl("@label", { fg = colors.mauve })
hl("@string", { fg = colors.yellow })
hl("@string.escape", { fg = colors.pink })
hl("@string.regexp", { fg = colors.pink })
hl("@character", { fg = colors.yellow })
hl("@number", { fg = colors.peach })
hl("@boolean", { fg = colors.peach })
hl("@float", { fg = colors.peach })
hl("@function", { fg = colors.green })
hl("@function.builtin", { fg = colors.green })
hl("@function.macro", { fg = colors.pink })
hl("@function.method", { fg = colors.green })
hl("@constructor", { fg = colors.blue })
hl("@operator", { fg = colors.sky })
hl("@keyword", { fg = colors.mauve })
hl("@keyword.function", { fg = colors.mauve, italic = true })
hl("@keyword.return", { fg = colors.mauve })
hl("@keyword.operator", { fg = colors.mauve })
hl("@conditional", { fg = colors.mauve, italic = true })
hl("@repeat", { fg = colors.mauve, italic = true })
hl("@exception", { fg = colors.red })
hl("@type", { fg = colors.blue })
hl("@type.builtin", { fg = colors.blue })
hl("@type.qualifier", { fg = colors.mauve })
hl("@attribute", { fg = colors.pink })
hl("@property", { fg = colors.text })
hl("@comment", { fg = colors.overlay1, italic = true })
hl("@punctuation.delimiter", { fg = colors.overlay2 })
hl("@punctuation.bracket", { fg = colors.overlay2 })
hl("@punctuation.special", { fg = colors.pink })
hl("@tag", { fg = colors.mauve })
hl("@tag.attribute", { fg = colors.yellow })
hl("@tag.delimiter", { fg = colors.overlay2 })

-- LSP
hl("DiagnosticError", { fg = colors.red })
hl("DiagnosticWarn", { fg = colors.yellow })
hl("DiagnosticInfo", { fg = colors.blue })
hl("DiagnosticHint", { fg = colors.green })
hl("DiagnosticUnderlineError", { sp = colors.red, undercurl = true })
hl("DiagnosticUnderlineWarn", { sp = colors.yellow, undercurl = true })
hl("DiagnosticUnderlineInfo", { sp = colors.blue, undercurl = true })
hl("DiagnosticUnderlineHint", { sp = colors.green, undercurl = true })
hl("LspReferenceText", { bg = colors.surface1 })
hl("LspReferenceRead", { bg = colors.surface1 })
hl("LspReferenceWrite", { bg = colors.surface1 })
hl("LspSignatureActiveParameter", { fg = colors.peach, bold = true })

-- Telescope
hl("TelescopeSelection", { fg = colors.mauve, bg = colors.surface0 })
hl("TelescopeSelectionCaret", { fg = colors.mauve })
hl("TelescopeMatching", { fg = colors.mauve, bold = true })
hl("TelescopeBorder", { fg = colors.mauve })
hl("TelescopePromptBorder", { fg = colors.mauve })
hl("TelescopeResultsBorder", { fg = colors.mauve })
hl("TelescopePreviewBorder", { fg = colors.mauve })
hl("TelescopePromptPrefix", { fg = colors.mauve })

-- Neo-tree
hl("NeoTreeDirectoryIcon", { fg = colors.mauve })
hl("NeoTreeRootName", { fg = colors.mauve, bold = true })
hl("NeoTreeFileName", { fg = colors.text })
hl("NeoTreeFileIcon", { fg = colors.mauve })
hl("NeoTreeFloatBorder", { fg = colors.mauve })
hl("NeoTreeCursorLine", { bg = colors.surface0 })

-- Dashboard
hl("DashboardHeader", { fg = colors.mauve })
hl("DashboardCenter", { fg = colors.mauve })
hl("DashboardShortCut", { fg = colors.mauve })
hl("DashboardFooter", { fg = colors.mauve })

-- BufferLine
hl("BufferLineIndicatorSelected", { fg = colors.mauve })
hl("BufferLineFill", { bg = transparent_bg and "NONE" or colors.base })

-- IndentBlankline
hl("IblIndent", { fg = colors.surface0 })
hl("IblScope", { fg = colors.mauve })

-- Noice
hl("NoiceCmdlinePopupBorder", { fg = colors.mauve })
hl("NoiceCmdlineIcon", { fg = colors.mauve })

-- WhichKey
hl("WhichKeyGroup", { fg = colors.mauve })
hl("WhichKey", { fg = colors.mauve })

-- Cmp
hl("CmpItemAbbrMatch", { fg = colors.mauve, bold = true })
hl("CmpItemAbbrMatchFuzzy", { fg = colors.mauve, bold = true })
hl("CmpItemKindSnippet", { fg = colors.base, bg = colors.mauve })
hl("CmpItemKindKeyword", { fg = colors.base, bg = colors.mauve })
hl("CmpItemKindText", { fg = colors.base, bg = colors.mauve })
hl("CmpItemKindMethod", { fg = colors.base, bg = colors.mauve })
hl("CmpItemKindConstructor", { fg = colors.base, bg = colors.mauve })
hl("CmpItemKindFunction", { fg = colors.base, bg = colors.mauve })
hl("CmpItemKindFolder", { fg = colors.base, bg = colors.mauve })
hl("CmpItemKindModule", { fg = colors.base, bg = colors.mauve })
hl("CmpItemKindConstant", { fg = colors.base, bg = colors.mauve })
hl("CmpItemKindField", { fg = colors.base, bg = colors.mauve })
hl("CmpItemKindProperty", { fg = colors.base, bg = colors.mauve })
hl("CmpItemKindEnum", { fg = colors.base, bg = colors.mauve })
hl("CmpItemKindUnit", { fg = colors.base, bg = colors.mauve })
hl("CmpItemKindClass", { fg = colors.base, bg = colors.mauve })
hl("CmpItemKindVariable", { fg = colors.base, bg = colors.mauve })
hl("CmpItemKindFile", { fg = colors.base, bg = colors.mauve })
hl("CmpItemKindInterface", { fg = colors.base, bg = colors.mauve })
hl("CmpItemKindColor", { fg = colors.base, bg = colors.mauve })
hl("CmpItemKindReference", { fg = colors.base, bg = colors.mauve })
hl("CmpItemKindEnumMember", { fg = colors.base, bg = colors.mauve })
hl("CmpItemKindStruct", { fg = colors.base, bg = colors.mauve })
hl("CmpItemKindValue", { fg = colors.base, bg = colors.mauve })
hl("CmpItemKindEvent", { fg = colors.base, bg = colors.mauve })
hl("CmpItemKindOperator", { fg = colors.base, bg = colors.mauve })
hl("CmpItemKindTypeParameter", { fg = colors.base, bg = colors.mauve })

-- Apply opacity settings (Neovide)
if opacity_ok then
  opacity_config.setup()
end
